"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let Db=2463534242,Ee=()=>{let x=Db;x^=x<<13;x^=x>>>17;x^=x<<5;Db=x;return x;},B3=f=>function(){return f(this);},CT=f=>function(p1){return f(this,p1);},DI=f=>function(){let args=Array.prototype.slice.apply(arguments);C9(function()
{f.apply(this,args);});},DG=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=BL(Bc(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Bl(args[i]);}C9(()=>{f.call(null,javaArgs);},callback);},CO=target=>target.$clinit=()=>{},ED=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName
+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=Bc();}return function(){superclass.call(this);};},BI=cls=>Ej(cls),Bc=()=>D,CP=()=>{{return DA();}},BK=t=>{{return Dk(t);}},W=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},EK=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},B1=(name,binaryName)=>{let cls=EK();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName
=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},EV=B1("boolean","Z"),BX=B1("char","C"),Cq=B1("int","I"),Y=(a,b)=>a>b?1:a<b? -1:a===b?0:1,M=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Dh=BigInt(0),Ba=val=>BigInt.asIntN(64,BigInt(val|0)),Bh=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),Bj=val=>
Number(BigInt.asIntN(32,val))|0,Cu=(a,b)=>a>b,DJ=(a,b)=>a>=b,C4=(a,b)=>BigInt.asIntN(64,a+b),CX=(a,b)=>BigInt.asIntN(64,a -b),BL=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (BB(cls))(data);},Bz=sz=>new EB(new Uint16Array(sz)),Bo=sz=>new Df(new Int32Array(sz)),CZ=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new Df(buffer);},EP=sz=>new D$(new Int8Array(sz)),BB=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(Bc()).call(this);this.data=data;}JavaArray.prototype
=Object.create((Bc()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.b8=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (BB(this.type))(dataCopy);};let name
="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[Bc()],primitive:false,superclass:Bc(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},Ch,Eu=strings=>{E8();Ch=new Array(strings.length);for(let i=0;i<strings.length;++i){Ch[i]=C5(Bl(strings[i]));}},J=index=>Ch[index],Ce=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i
<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bl=str=>str===null?null:D7(str),BM=str=>str===null?null:str.bg,E8=()=>(()=>{})(),C5;
{C5=str=>str;}let S=ex=>{throw Cs(ex);},Bw=Symbol("javaException"),Cs=ex=>{if(!ex.$jsException){X(ex);}return ex.$jsException;},X=ex=>{let javaCause=E2(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Bd("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bw]=ex;ex.$jsException=err;CY(err,ex);},CY=(err,ex)=>{if(typeof D3==="function"&&err.stack){let stack=D3(err.stack);let javaStack
=BL(Eo(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=Ez(Bl(element.className),Bl(element.methodName),Bl(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){ET(ex,javaStack);}}},Bd;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Bd=function Bd(message,cause){let self=Reflect.construct(Error,[void 0,cause],Bd);Object.setPrototypeOf(self,Bd.prototype);self[defaultMessage]=message;return self;}
;Bd.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Bd},message:{get(){try {let javaException=this[Bw];if(typeof javaException==='object'){let javaMessage=Dw(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Bd=Error;}let DN=e=>e instanceof Error&&typeof e[Bw]==='object'?e[Bw]:null,G=err=>
{let ex=err[Bw];if(!ex){ex=DY(Bl("(JavaScript) "+err.toString()));err[Bw]=ex;ex.$jsException=err;CY(err,ex);}return ex;},DY=message=>El(message),Dw=t=>EW(t),E2=t=>E7(t),Eo=()=>Bc(),Ez=(className,methodName,fileName,lineNumber)=>{{return null;}},ET=(e,stack)=>{},CQ=null,Dy=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}CQ=packages;},CW=data=>{let packages=CQ;let i=
0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags
&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit
=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}};
function Q(runner){this.status=3;this.stack=[];this.suspendCallback=null;this.runner=runner;this.attribute=null;this.completeCallback=null;}
Q.prototype.push=function(){for(let i=0;i<arguments.length;++i){this.stack.push(arguments[i]);}return this;};Q.prototype.s=Q.prototype.push;Q.prototype.pop=function(){return this.stack.pop();};Q.prototype.l=Q.prototype.pop;Q.prototype.isResuming=function(){return this.status===2;};Q.prototype.isSuspending=function(){return this.status===1;};Q.prototype.suspend=function(callback){this.suspendCallback=callback;this.status=1;};Q.prototype.start=function(callback){if(this.status!==3){throw new Error("Thread already started");}if
(BF!==null){throw new Error("Another thread is running");}this.status=0;this.completeCallback=callback?callback:result=>{if(result instanceof Error){throw result;}};this.run();};Q.prototype.resume=function(){if(BF!==null){throw new Error("Another thread is running");}this.status=2;this.run();};Q.prototype.run=function(){BF=this;let result;try {result=this.runner();}catch(e){result=e;}finally {BF=null;}if(this.suspendCallback!==null){let self=this;let callback=this.suspendCallback;this.suspendCallback=null;callback(()=>
self.resume());}else if(this.status===0){this.completeCallback(result);}};let T=()=>{let thread=K();return thread!=null&&thread.isSuspending();},Bg=()=>{let thread=K();return thread!=null&&thread.isResuming();},Cy=()=>{let nativeThread=K();if(nativeThread===null){throw new Error("Suspension point reached from non-threading context "+"(perhaps, from native JS method). See https://teavm.org/docs/runtime/coroutines.html "+"('Interaction with JavaScript' section)");}return nativeThread;},C9=(runner,callback)=>(new Q(runner)).start(callback),BF
=null,K=()=>BF,Be=()=>{throw new Error("Invalid recorded state");};
function D(){this.bi=null;this.$id$=0;}
let Fj=b=>{let c,d;c=F;if(c===null)return;if(b.bi===null){d=new BN;d.bh=c;b.bi=d;}b=b.bi;d=b.bh;if(d===null)b.bh=c;else if(d!==c){d=new CA;X(d);d.bn=1;d.bm=1;d.bF=J(0);S(d);}b.bk=b.bk+1|0;},Fc=b=>{let c,d;if(F===null)return;if(!BE(b)){c=b.bi;if(c.bh===F){d=c.bk-1|0;c.bk=d;if(!d)c.bh=null;BE(b);return;}}b=new BP;X(b);b.bn=1;b.bm=1;S(b);},BW=b=>{let c,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:c=1;$p=1;case 1:EH(b,c);if(T()){break _;}return;default:Be();}}K().s(b,
c,$p);},EH=(b,c)=>{let d,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:if(b.bi===null){d=new BN;d.bh=F;b.bi=d;}d=b.bi;if(d.bh===null)d.bh=F;if(d.bh===F){d.bk=d.bk+c|0;return;}$p=1;case 1:DE(b,c);if(T()){break _;}return;default:Be();}}K().s(b,c,d,$p);},Es=(b,c,d)=>{let e,f,g;e=F;f=b.bi;if(f===null){f=new BN;f.bh=e;b.bi=f;if(e!==e)F=e;F.bo=U();b=b.bi;b.bk=b.bk+c|0;b=null;d.bu.e(b);return;}if(f.bh===null){f.bh=e;if(e!==e)F=e;F.bo=U();b=b.bi;b.bk=b.bk+c|0;b
=null;d.bu.e(b);return;}if(f.bq===null)f.bq=DP();f=f.bq;g=new Dc;g.bN=e;g.bO=b;g.bL=c;g.bM=d;d=g;f.push(d);},Br=b=>{EI(b,1);},EI=(b,c)=>{let d;if(!BE(b)){d=b.bi;if(d.bh===F){c=d.bk-c|0;d.bk=c;if(c>0)return;d.bh=null;d=d.bq;if(d!==null&&!(d.length?0:1)){d=new CB;d.bJ=b;Cb(d,0);}else BE(b);return;}}b=new BP;X(b);b.bn=1;b.bm=1;S(b);},D9=b=>{let c,d,e;if(!BE(b)){c=b.bi;if(c.bh===null){b=c.bq;if(b!==null&&!(b.length?0:1)){b=c.bq.shift();if(b!==null&&!(b instanceof Bc()))b=CC(b);d=b;c.bq=null;b=d;c=b.bN;d=b.bO;e=
b.bL;b=b.bM;if(F!==c)F=c;F.bo=U();d=d.bi;d.bh=c;d.bk=d.bk+e|0;c=null;b.bu.e(c);}return;}}},BE=a=>{let b,c;b=a.bi;if(b===null)return 1;a:{if(b.bh===null){c=b.bq;if(!(c!==null&&!(c.length?0:1))){b=b.bI;if(b===null)break a;if(b.length?0:1)break a;}}return 0;}a.bi=null;return 1;},Ek=a=>{return;},E1=()=>{let a=new D();Ek(a);return a;},EL=a=>{let b,c,d,e,f,g,h,i,j;b=a;if(!b.$id$)b.$id$=Ee();c=Eh(a.$id$,4);b=new C1;b.bs=Bz(16);d=b.bp;e=b;f=J(1);e=e;Cz(e,d,f);Cz(e,b.bp,c===null?J(2):c);f=new O;g=b.bs;h=g.data;i=b.bp;j
=h.length;if(i>=0&&i<=(j-0|0)){f.bg=Ce(g.data,0,i);return f;}b=new BU;D8(b);b.bn=1;b.bm=1;ES(b);S(b);},Co=a=>{let b,c;b=a.bi;if(!(b!==null&&b.bh===F?1:0)){b=new BP;X(b);b.bn=1;b.bm=1;S(b);}b=b.bI;if(b===null)return;while(!(b.length?0:1)){c=b.shift();if(c!==null&&!(c instanceof Bc()))c=CC(c);c=c;if(!c.n())Cb(c,0);}a.bi.bI=null;},DE=(b,c)=>{let thread=Cy();let javaThread=CP();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback
=function(){};callback.e=val=>{thread.attribute=val;BK(javaThread);thread.resume();};callback.be=e=>{thread.attribute=Cs(e);BK(javaThread);thread.resume();};callback=De(callback);thread.suspend(()=>{try {Es(b,c,callback);;}catch($e){callback.be($e);}});return null;},Ct=E(0),CN=E(0);
function CM(){D.call(this);this.b7=null;}
let Ej=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new CM;c.b7=b;b.classObject=c;}return c;},Ea=E(),V=(b,c)=>{let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},EJ=E(),E_=b=>{setTimeout(()=>{DI(Dl)(b);},0);},Dl=b=>{let $p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:b.o();if(T()){break _;}return;default:Be();}}K().s(b,
$p);},Cb=(b,c)=>{setTimeout(()=>{Dl(b);},c);},DP=()=>{return [];};
function Bx(){let a=this;D.call(a);a.bF=null;a.b3=null;a.bn=0;a.bm=0;}
let ES=a=>{return a;},D8=a=>{X(a);},EW=a=>{return a.bF;},E7=a=>{let b;b=a.b3;if(b===a)b=null;return b;},I=E(Bx),R=E(I),DR=(a,b)=>{X(a);a.bn=1;a.bm=1;a.bF=b;},El=a=>{let b=new R();DR(b,a);return b;},E3=E(R),By=E(0),BT=E(0),Cc=E(0),O=E(),CF=null,C_=null,C3=null,DH=(a,b)=>{a.bg=Ce(b.data,0,b.data.length);},Fe=a=>{let b=new O();DH(b,a);return b;},Ed=(a,b)=>{a.bg=b;},D7=a=>{let b=new O();Ed(b,a);return b;},Fh=()=>{let b;CF=Bz(0);b=new O;b.bg="";C_=b;C3=new BV;},B0=E(),Et=E(B0),C7=null,EQ=b=>{let c,d;if(!b)return 32;c
=0;d=b>>>16|0;if(d)c=16;else d=b;b=d>>>8|0;if(!b)b=d;else c=c|8;d=b>>>4|0;if(!d)d=b;else c=c|4;b=d>>>2|0;if(!b)b=d;else c=c|2;if(b>>>1|0)c=c|1;return (32-c|0)-1|0;},Fg=()=>{C7=BI(Cq);};
function Cg(){let a=this;D.call(a);a.bs=null;a.bp=0;}
let Cz=(a,b,c)=>{let d,e,f,g;if(b>=0&&b<=a.bp){if(c===null)c=J(2);else if(c.bg.length?0:1)return a;d=a.bp+c.bg.length|0;DS(a,d);e=a.bp-1|0;while(e>=b){a.bs.data[e+c.bg.length|0]=a.bs.data[e];e=e+(-1)|0;}a.bp=a.bp+c.bg.length|0;e=0;a:{while(e<c.bg.length){f=a.bs;g=b+1|0;if(e<0)break a;if(e>=c.bg.length)break a;f.data[b]=c.bg.charCodeAt(e);e=e+1|0;b=g;}return a;}c=new Cl;X(c);c.bn=1;c.bm=1;S(c);}c=new Cl;X(c);c.bn=1;c.bm=1;S(c);},DS=(a,b)=>{let c,d,e,f,g,h;c=a.bs.data;d=c.length;if(d>=b)return;if(d>=1073741823)e
=2147483647;else{f=d*2|0;e=5;if(f>e)e=f;if(b>e)e=b;}g=Bz(e);if(e<d)d=e;h=g.data;b=0;while(b<d){h[b]=c[b];b=b+1|0;}a.bs=g;},Dr=E(0),C1=E(Cg),D2=E(),Er=E(),Em=E(),Dd=E(),Bk=null,Bu=null,BH=null,H=null,BR=null,N=null,Cp=0,BZ=null,P=()=>{P=CO(Dd);EX();},Eg=b=>{let c,d,e,f,g,h,i;P();c=window;Bu=c;d=c.document;BH=d;c=d.getElementById(BM(BZ));e=Bo(2);b=e.data;N=e;b[0]=Bq;b[1]=Bn;if(c===null)H=Di(BH.body);else if(!(c instanceof HTMLCanvasElement?1:0)){c.removeAttribute("id");H=Di(c);if(c.hasAttribute("fullscreen")?
1:0){c.removeAttribute("fullscreen");H.setAttribute("fullscreen","");}}else{H=c;b=(Dm(c)).data;if(b[0])N.data[0]=H.width;else H.width=N.data[0];if(b[1])N.data[1]=H.height;else H.height=N.data[1];}BR=H.getContext("2d");if(!(H.hasAttribute("fullscreen")?1:0))CS();else{N.data[0]=Bu.innerWidth;N.data[1]=Bu.innerHeight;H.width=N.data[0];H.height=N.data[1];CH(BR,!!0);Cp=1;}d=new Dg;f=H;c=BR;d.b4=f;d.bZ=c;g=new Dp;g.bA=c;g.bC=f;d.bX=g;d.bl=Bo(32767);Bk=d;c=new Cm;f=null;c.br=new D;c.bv=1;c.bT=f;c.bD=d;h=BD;BD=h+1|
0;c.bR=Ba(h);d=new Ds;d.bK=c;E_(d);H.tabIndex=0;H.focus();c=H;f=new B$;g="addEventListener";d="mousedown";i=!(f instanceof L)?f:f.bj;c[g](d,V(i,"handleEvent"));c=H;f=new B8;g="addEventListener";d="mouseup";i=!(f instanceof L)?f:f.bj;c[g](d,V(i,"handleEvent"));c=H;f=new B9;g="addEventListener";d="mousemove";i=!(f instanceof L)?f:f.bj;c[g](d,V(i,"handleEvent"));c=H;f=new B6;g="addEventListener";d="mouseleave";i=!(f instanceof L)?f:f.bj;c[g](d,V(i,"handleEvent"));c=H;f=new B7;g="addEventListener";d="contextmenu";i
=!(f instanceof L)?f:f.bj;c[g](d,V(i,"handleEvent"));c=H;f=new B4;g="addEventListener";d="keydown";i=!(f instanceof L)?f:f.bj;c[g](d,V(i,"handleEvent"));c=H;f=new B5;g="addEventListener";d="keyup";i=!(f instanceof L)?f:f.bj;c[g](d,V(i,"handleEvent"));c=Bu;f=new B_;g="addEventListener";d="resize";i=!(f instanceof L)?f:f.bj;c[g](d,V(i,"handleEvent"));c=BH;f=new Ca;c.addEventListener("click",V(!(f instanceof L)?f:f.bj,"handleEvent"));},Di=b=>{let c,d;P();c=BH.createElement("canvas");d=BM(BZ);c.id=d;d=N.data[0];c.width
=d;d=N.data[1];c.height=d;b.appendChild(c);return c;},CS=()=>{let b,c,d;P();b=Dm(H);c=Bu.innerWidth;d=Bu.innerHeight;if(!(!Cp&&b.data[0]&&c>=N.data[0])){H.width=c;N.data[0]=c;}if(!(!Cp&&b.data[1]&&d>=N.data[1])){H.height=d;N.data[1]=d;}CH(BR,!!0);},EO=b=>{let c,d;P();c=new Bi;c.bt=402;d=b.keyCode;if(d>=65&&d<=90)d=d+32|0;c.bB=d;Bt(Bk,c);b.preventDefault();},Ec=b=>{let c,d;P();c=new Bi;c.bt=401;d=b.keyCode;if(d>=65&&d<=90)d=d+32|0;c.bB=d;Bt(Bk,c);b.preventDefault();},DF=b=>{let c,d;P();c=(BY(H,b.offsetX,b.offsetY)).data;d
=new Bi;d.bt=502;d.bx=c[0];d.bw=c[1];d.bE=b.button!=2?0:4;Bt(Bk,d);b.preventDefault();},EE=b=>{let c,d;P();c=(BY(H,b.offsetX,b.offsetY)).data;d=new Bi;d.bt=501;d.bx=c[0];d.bw=c[1];d.bE=b.button!=2?0:4;Bt(Bk,d);b.preventDefault();},EX=()=>{let b;CF=Bz(0);b=new O;b.bg="";C_=b;C3=new BV;C7=BI(Cq);BC=214;Bs=120;Bq=856;Bn=480;C6=BI(BX);Dj=BL(Cn,128);Dz();BZ=J(3);},EU=E(),Eh=(b,c)=>{let d,e,f,g,h,i,j,k,l;if(!b)return J(4);d=1<<c;e=d-1|0;f=(((32-EQ(b)|0)+c|0)-1|0)/c|0;g=Bz(f);h=g.data;i=M(f-1|0,c);j=0;while(i>=0){k
=j+1|0;h[j]=DZ((b>>>i|0)&e,d);i=i-c|0;j=k;}l=new O;l.bg=Ce(g.data,0,h.length);return l;},DT=E(),BC=0,Bs=0,Bq=0,Bn=0,Fd=()=>{BC=214;Bs=120;Bq=856;Bn=480;},DO=E(),BY=(b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o;e=b.width;f=b.height;g=BC;h=e/g|0;i=f/Bs|0;if(h<i)i=h;j=i;k=g*j;g=Bj(Bh(k+Bp(k)*0.5));j=Bs*j;i=Bj(Bh(j+Bp(j)*0.5));h=(e-g|0)/2|0;l=(f-i|0)/2|0;if(c>=h&&c<(h+g|0)&&d>=l&&d<(l+i|0)){k=(c-h|0)/g;m=(d-l|0)/i;j=k*Bq;n=Bj(Bh(j+Bp(j)*0.5));j=m*Bn;o=Bj(Bh(j+Bp(j)*0.5));if(n<0)c=0;else{c=Bq-1|0;if(n<=c)c=n;}if(o<0)o=0;else
{d=Bn;if(o>d)o=d-1|0;}return CZ([c,o]);}return CZ([(-1),(-1)]);},Dm=b=>{let c,d;c=EP(2);d=c.data;d[0]=0;d[1]=0;if(b.width)d[0]=1;if(b.height)d[1]=1;return c;},CH=(b,c)=>{b.imageSmoothingEnabled=c;if(b.mozImageSmoothingEnabled!==undefined)b.mozImageSmoothingEnabled=c;if(b.webkitImageSmoothingEnabled!==undefined)b.webkitImageSmoothingEnabled=c;if(b.msImageSmoothingEnabled!==undefined)b.msImageSmoothingEnabled=c;};
function B2(){let a=this;D.call(a);a.b4=null;a.bZ=null;a.bX=null;}
let Ey=a=>{return 1;},EM=a=>{return a.bX;},Cr=E(0);
function Dg(){B2.call(this);this.bl=null;}
let DB=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv,bw,bx,by,bz,bA,bB,bC,bD,bE,bF,bG,bH,bI,bJ,bK,bL,bM,bN,bO,bP,bQ,bR,bS,bT,bU,bV,bW,bX,bY,bZ,b0,b1,b2,b3,b4,b5,$$je,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b5=$T.l();b4=$T.l();b3=$T.l();b2=$T.l();b1=$T.l();b0=$T.l();bZ=$T.l();bY=$T.l();bX=$T.l();bW=$T.l();bV=$T.l();bU=$T.l();bT=$T.l();bS=$T.l();bR=$T.l();bQ=$T.l();bP=$T.l();bO=$T.l();bN=$T.l();bM=$T.l();bL=$T.l();bK=$T.l();bJ=$T.l();bI
=$T.l();bH=$T.l();bG=$T.l();bF=$T.l();bE=$T.l();bD=$T.l();bC=$T.l();bB=$T.l();bA=$T.l();bz=$T.l();by=$T.l();bx=$T.l();bw=$T.l();bv=$T.l();bu=$T.l();bt=$T.l();bs=$T.l();br=$T.l();bq=$T.l();bp=$T.l();bo=$T.l();bn=$T.l();bm=$T.l();bl=$T.l();bk=$T.l();bj=$T.l();bi=$T.l();bh=$T.l();bg=$T.l();bf=$T.l();be=$T.l();bd=$T.l();bc=$T.l();bb=$T.l();ba=$T.l();z=$T.l();y=$T.l();x=$T.l();w=$T.l();v=$T.l();u=$T.l();t=$T.l();s=$T.l();r=$T.l();q=$T.l();p=$T.l();o=$T.l();n=$T.l();m=$T.l();l=$T.l();k=$T.l();j=$T.l();i=$T.l();h=
$T.l();g=$T.l();f=$T.l();e=$T.l();d=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:a:{try{b=Du();c=DC(214,120,1);d=EC(Ep(D4(c)));e=Bo(262144);D0(b,Ba(18295169));f=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}g=e.data;while(true){try{if(f>=262144)break;g[f]=((f/64|0)%64|0)<=(32+Bf(b,8)|0)?0:Bf(b,8)+1|0;f=f+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{h=Bo(12288);i=1;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}
else{throw $$e;}}e=h.data;while(true){try{if(i>=16)break;j=255-Bf(b,96)|0;k=0;while(k<48){l=0;while(l<16){m=9858122;n=Y(i,4);if(!n)m=8355711;if(!(!n&&Bf(b,3)))j=255-Bf(b,96)|0;n=Y(i,1);if(!n&&k<((((M(l,l)*3|0)+(l*81|0)|0)>>2&3)+18|0))m=6990400;else if(!n&&k<((((M(l,l)*3|0)+(l*81|0)|0)>>2&3)+19|0))j=(j*2|0)/3|0;b:{if(i==7){c:{m=6771249;if(l>0&&l<15){if(k>0&&k<15)break c;if(k>32&&k<47)break c;}if(Bf(b,2))break b;j=M(j,150-((l&1)*100|0)|0)/100|0;break b;}m=12359778;o=l-7|0;p=(k&15)-7|0;if(o<0)o=1-o|0;if(p<0)p=
1-p|0;if(p<=o)p=o;j=(196-Bf(b,32)|0)+((p%3|0)*32|0)|0;}}if(i==5){m=11876885;if(!(((l+((k/4|0)*4|0)|0)%8|0)&&(k%4|0)))m=12365733;}n=k<32?j:j/2|0;if(i==8){m=5298487;if(!Bf(b,2)){m=0;n=255;}}n=(M(m>>16&255,n)/255|0)<<16|(M(m>>8&255,n)/255|0)<<8|(M(m&255,n)/255|0);e[(l+(k*16|0)|0)+((i*256|0)*3|0)|0]=n;l=l+1|0;}k=k+1|0;}i=i+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{q=96.5;r=65.0;s=96.5;t=0.0;u=0.0;v=0.0;w=U();x=0;y=0.0;z=0.0;ba=y;bb=BG(ba);bc=BO(ba);ba=z;bd=BG(ba);be
=BO(ba);while(Cu(CX(U(),w),Ba(10))){h=a.bl.data;if(h[2]>0){bf=(h[2]-428|0)/214.0*2.0;bg=(h[3]-240|0)/120.0*2.0;bh=CV(bf*bf+bg*bg)-1.2000000476837158;if(bh<0.0)bh=0.0;if(bh>0.0){y=y+bf*bh/400.0;z=z-bg*bh/400.0;if(z<(-1.5700000524520874))z=(-1.5700000524520874);if(z>1.5700000524520874)z=1.5700000524520874;}}w=C4(w,Ba(10));h=a.bl.data;bf=0.0+(h[119]-h[115]|0)*0.019999999552965164;bg=0.0+(h[100]-h[97]|0)*0.019999999552965164;bh=t*0.5;bi=u*0.9900000095367432;bj=v*0.5;t=bh+bb*bf+bc*bg;v=bj+bc*bf-bb*bg;u=bi+0.003000000026077032;bk
=0;while(bk<3){bl=q+t*(((bk+0|0)%3|0)/2|0);bm=bk+1|0;bn=r+u*((bm%3|0)/2|0);bo=s+v*(((bk+2|0)%3|0)/2|0);bp=0;d:{e:{while(bp<12){bq=(bl+(bp>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;br=(bn+((bp>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bs=(bo+(bp>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bq<0)break e;if(br<0)break e;if(bs<0)break e;if(bq>=64)break e;if(br>=64)break e;if(bs>=64)break e;if(g[(bq+(br*64|0)|0)+(bs*4096|0)|0]>0)break e;bp=bp+1|0;}break d;}if(bk!=1){bl=q;bn=r;bo
=s;}else if(h[32]>0&&u>0.0){h[32]=0;u=(-0.10000000149011612);bl=q;bn=r;bo=s;}else{u=0.0;bl=q;bn=r;bo=s;}}bk=bm;q=bl;r=bn;s=bo;}}h=a.bl.data;if(h[1]>0&&(-1)>0){g[(-1)]=0;h[1]=0;}if(h[0]>0&&(-1)>0){g[(-1)+x|0]=1;h[0]=0;}bt=0;while(bt<12){bu=(q+(bt>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bv=(r+((bt>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bw=(s+(bt>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bu>=0&&bv>=0&&bw>=0&&bu<64&&bv<64&&bw<64)g[(bu+(bv*64|0)|0)+(bw*4096|0)|0]=0;bt=bt
+1|0;}bx=(-1);by=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}bh=1.0*be;bl=1.0*bd;while(true){try{if(by>=214)break;bz=(by-107|0)/90.0;bA=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}bn=bz*bc;bB=bz*bb;while(true){try{if(bA>=120)break;bC=(bA-60|0)/90.0;bD=bh+bC*bd;bE=bC*be-bl;bF=bn+bD*bb;bG=bD*bc-bB;bH=0;bI=255;bJ=20.0;bK=5.0;bL=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}while(true){try{if(bL>=3)break;n=Y(bL,1);bf=n?bF:bE;l
=Y(bL,2);if(!l)bf=bG;k=Y(bf,0.0);if(k<0)bf= -bf;bM=1.0/bf;bN=bF*bM;bi=bE*bM;bj=bG*bM;bO=q-(q|0);if(!n)bO=r-(r|0);if(!l)bO=s-(s|0);if(k>0)bO=1.0-bO;bP=bM*bO;bQ=q+bN*bO;bR=r+bi*bO;bS=s+bj*bO;if(k<0){if(!bL)bQ=bQ-1.0;if(!n)bR=bR-1.0;if(!l)bS=bS-1.0;}}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}o=Y(bi,0.0);f:{try{while(true){ba=bP;if(ba>=bJ)break f;bT=(bQ|0)-64|0;bU=(bR|0)-64|0;bV=(bS|0)-64|0;if(bT<0)break f;if(bU<0)break f;if(bV<0)break f;if(bT>=64)break f;if(bU>=64)break f;if(bV>=64)break;bW
=(bT+(bU*64|0)|0)+(bV*4096|0)|0;bX=g[bW];if(bX>0){p=((bQ+bS)*16.0|0)&15;l=((bR*16.0|0)&15)+16|0;if(!n){p=(bQ*16.0|0)&15;l=(bS*16.0|0)&15;if(o<0)l=l+32|0;}g:{bY=16777215;if(bW==(-1)){if(p<=0)break g;j=l%16|0;if(j<=0)break g;if(p>=15)break g;if(j>=15)break g;}bY=e[(p+(l*16|0)|0)+((bX*256|0)*3|0)|0];}if(bP>=bK)bW=bx;else if(by!=(h[2]/4|0))bW=bx;else if(bA!=(h[3]/4|0))bW=bx;else{bZ=1;if(k>0)bZ=(-1);x=bZ<<(6*bL|0);bK=bP;}if(bY<=0)bx=bW;else{bI=M(255-(bP/20.0*255.0|0)|0,255-(((bL+2|0)%3|0)*50|0)|0)/255|0;bx=bW;bH
=bY;bJ=ba;}}bQ=bQ+bN;bR=bR+bi;bS=bS+bj;bP=bP+bM;}break f;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bL=bL+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b0=d.data;b1=M(bH>>16&255,bI)/255|0;b2=M(bH>>8&255,bI)/255|0;b3=M(bH&255,bI)/255|0;b0[by+(bA*214|0)|0]=b1<<16|b2<<8|b3;bA=bA+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{by=by+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}
else{throw $$e;}}}try{b4=Ba(2);$p=1;continue _;}catch($$e){$$je=G($$e);if($$je instanceof I){}else{throw $$e;}}}return;case 1:a:{h:{try{DL(b4);if(T()){break _;}b=a;if(Ey(b))break h;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}return;}try{EZ(EM(b),c,0,0,856,480,null);b5=bx;ba=y;bb=BG(ba);bc=BO(ba);ba=z;bd=BG(ba);be=BO(ba);while(Cu(CX(U(),w),Ba(10))){h=a.bl.data;if(h[2]>0){bf=(h[2]-428|0)/214.0*2.0;bg=(h[3]-240|0)/120.0*2.0;bh=CV(bf*bf+bg*bg)-1.2000000476837158;if(bh<0.0)bh=0.0;if(bh
>0.0){y=y+bf*bh/400.0;z=z-bg*bh/400.0;if(z<(-1.5700000524520874))z=(-1.5700000524520874);if(z>1.5700000524520874)z=1.5700000524520874;}}w=C4(w,Ba(10));h=a.bl.data;bf=0.0+(h[119]-h[115]|0)*0.019999999552965164;bg=0.0+(h[100]-h[97]|0)*0.019999999552965164;bh=t*0.5;bi=u*0.9900000095367432;bj=v*0.5;t=bh+bb*bf+bc*bg;v=bj+bc*bf-bb*bg;u=bi+0.003000000026077032;bk=0;while(bk<3){bl=q+t*(((bk+0|0)%3|0)/2|0);bm=bk+1|0;bn=r+u*((bm%3|0)/2|0);bo=s+v*(((bk+2|0)%3|0)/2|0);bp=0;i:{j:{while(bp<12){bq=(bl+(bp>>0&1)*0.6000000238418579
-0.30000001192092896|0)-64|0;br=(bn+((bp>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bs=(bo+(bp>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bq<0)break j;if(br<0)break j;if(bs<0)break j;if(bq>=64)break j;if(br>=64)break j;if(bs>=64)break j;if(g[(bq+(br*64|0)|0)+(bs*4096|0)|0]>0)break j;bp=bp+1|0;}break i;}if(bk!=1){bl=q;bn=r;bo=s;}else if(h[32]>0&&u>0.0){h[32]=0;u=(-0.10000000149011612);bl=q;bn=r;bo=s;}else{u=0.0;bl=q;bn=r;bo=s;}}bk=bm;q=bl;r=bn;s=bo;}}h=a.bl.data;if(h[1]>0&&b5>0){g[b5]
=0;h[1]=0;}if(h[0]>0&&b5>0){g[b5+x|0]=1;h[0]=0;}bt=0;while(bt<12){bu=(q+(bt>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bv=(r+((bt>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bw=(s+(bt>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bu>=0&&bv>=0&&bw>=0&&bu<64&&bv<64&&bw<64)g[(bu+(bv*64|0)|0)+(bw*4096|0)|0]=0;bt=bt+1|0;}bx=(-1);by=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}bh=1.0*be;bl=1.0*bd;while(true){try{if(by>=214)break;bz=(by-107|0)/90.0;bA=0;}catch
($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}bn=bz*bc;bB=bz*bb;while(true){try{if(bA>=120)break;bC=(bA-60|0)/90.0;bD=bh+bC*bd;bE=bC*be-bl;bF=bn+bD*bb;bG=bD*bc-bB;bH=0;bI=255;bJ=20.0;bK=5.0;bL=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}while(true){try{if(bL>=3)break;n=Y(bL,1);bf=n?bF:bE;l=Y(bL,2);if(!l)bf=bG;k=Y(bf,0.0);if(k<0)bf= -bf;bM=1.0/bf;bN=bF*bM;bi=bE*bM;bj=bG*bM;bO=q-(q|0);if(!n)bO=r-(r|0);if(!l)bO=s-(s|0);if(k>0)bO=1.0-bO;bP=bM*bO;bQ=q+bN*bO;bR=r+
bi*bO;bS=s+bj*bO;if(k<0){if(!bL)bQ=bQ-1.0;if(!n)bR=bR-1.0;if(!l)bS=bS-1.0;}}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}o=Y(bi,0.0);k:{try{while(true){ba=bP;if(ba>=bJ)break k;bT=(bQ|0)-64|0;bU=(bR|0)-64|0;bV=(bS|0)-64|0;if(bT<0)break k;if(bU<0)break k;if(bV<0)break k;if(bT>=64)break k;if(bU>=64)break k;if(bV>=64)break;bW=(bT+(bU*64|0)|0)+(bV*4096|0)|0;bX=g[bW];if(bX>0){p=((bQ+bS)*16.0|0)&15;l=((bR*16.0|0)&15)+16|0;if(!n){p=(bQ*16.0|0)&15;l=(bS*16.0|0)&15;if(o<0)l=l+32|0;}l:{bY=16777215;if
(bW==b5){if(p<=0)break l;j=l%16|0;if(j<=0)break l;if(p>=15)break l;if(j>=15)break l;}bY=e[(p+(l*16|0)|0)+((bX*256|0)*3|0)|0];}if(bP>=bK)bW=bx;else if(by!=(h[2]/4|0))bW=bx;else if(bA!=(h[3]/4|0))bW=bx;else{bZ=1;if(k>0)bZ=(-1);x=bZ<<(6*bL|0);bK=bP;}if(bY<=0)bx=bW;else{bI=M(255-(bP/20.0*255.0|0)|0,255-(((bL+2|0)%3|0)*50|0)|0)/255|0;bx=bW;bH=bY;bJ=ba;}}bQ=bQ+bN;bR=bR+bi;bS=bS+bj;bP=bP+bM;}break k;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bL=bL+1|0;continue;}catch($$e){$$je=G($$e);if
($$je instanceof I){break a;}else{throw $$e;}}}try{b0=d.data;b1=M(bH>>16&255,bI)/255|0;b2=M(bH>>8&255,bI)/255|0;b3=M(bH&255,bI)/255|0;b0[by+(bA*214|0)|0]=b1<<16|b2<<8|b3;bA=bA+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{by=by+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b4=Ba(2);continue _;}catch($$e){$$je=G($$e);if($$je instanceof I){}else{throw $$e;}}}return;default:Be();}}K().s(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,
t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv,bw,bx,by,bz,bA,bB,bC,bD,bE,bF,bG,bH,bI,bJ,bK,bL,bM,bN,bO,bP,bQ,bR,bS,bT,bU,bV,bW,bX,bY,bZ,b0,b1,b2,b3,b4,b5,$p);},Bt=(a,b)=>{let c,d;a:{b:{c:{c=0;switch(b.bt){case 401:c=1;break c;case 501:c=1;d=a.bl.data;d[2]=b.bx;d[3]=b.bw;break b;case 503:case 506:d=a.bl.data;d[2]=b.bx;d[3]=b.bw;break a;case 505:break;case 402:break c;case 502:break b;default:break a;}a.bl.data[2]=0;break a;}a.bl.data[b.bB]=c;break a;}if((b.bE&4)<=0)a.bl.data[0]
=c;else a.bl.data[1]=c;}return 1;},Bm=E(0),Z=E(0),B$=E(),ER=(b,c)=>{b;EE(c);};
function L(){D.call(this);this.bj=null;}
let CC=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=Bl(typeof b);if(c===J(5))d=1;else if(!(J(5) instanceof O))d=0;else{e=J(5);d=c.bg!==e.bg?0:1;}a:{if(!d){if(c===J(6))d=1;else if(!(J(6) instanceof O))d=0;else{e=J(6);d=c.bg!==e.bg?0:1;}if(!d){d=0;break a;}}d=1;}BA();e=CK;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bj=b;e.set(b,new WeakRef(h));return h;}if(c===J(7))d=1;else if(!(J(7) instanceof O))d=0;else{e=J(7);d=
c.bg!==e.bg?0:1;}if(d){i=BS;j=CI;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bj=b;k=h;i.set(b,new WeakRef(k));j.register(k,b);return h;}if(c===J(8))d=1;else if(!(J(8) instanceof O))d=0;else{e=J(8);d=c.bg!==e.bg?0:1;}if(d){l=BJ;m=CR;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bj=b;k=h;l.set(b,new WeakRef(k));m.register(k,b);return h;}if(c===J(9))d=1;else if(!(J(9) instanceof O))d=
0;else{e=J(9);d=c.bg!==e.bg?0:1;}if(d){f=Cw;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bj=b;Cw=new WeakRef(h);return h;}}e=new L;e.bj=b;return e;},B8=E(),DX=(b,c)=>{b;DF(c);},B9=E(),D5=(b,c)=>{let d;b;P();d=(BY(H,c.offsetX,c.offsetY)).data;b=new Bi;b.bt=503;b.bx=d[0];b.bw=d[1];Bt(Bk,b);},B6=E(),Ev=(b,c)=>{b;P();b=new Bi;b.bt=505;Bt(Bk,b);},B7=E(),E4=(b,c)=>{b;P();c.preventDefault();},B4=E(),EA=(b,c)=>{b;Ec(c);},B5=E(),Dv=(b,c)=>{b;EO(c);},B_=E(),Ef=(b,c)=>{b;P();CS();},Ca
=E(),DK=(b,c)=>{b;P();H.focus();},Da=E(0),BV=E(),Cn=E(),C6=null,Dj=null,DZ=(b,c)=>{if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},Ff=()=>{C6=BI(BX);Dj=BL(Cn,128);},DD=E();
function Dp(){let a=this;D.call(a);a.bA=null;a.bC=null;}
let EZ=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m;if(e==Bq&&f==Bn){h=a.bC.width;i=a.bC.height;j=h;k=j/BC;l=i;m=EY(k,l/Bs);k=BC*m;e=Bj(Bh(k+Bp(k)*0.5));k=Bs*m;f=Bj(Bh(k+Bp(k)*0.5));c=(h-e|0)/2|0;d=(i-f|0)/2|0;a.bA.clearRect(0.0,0.0,j,l);}DQ(b);g=a.bA;b=b.by;j=c;l=d;k=e;m=f;g.drawImage(b,j,l,k,m);},BU=E(R);
function Cm(){let a=this;D.call(a);a.b1=null;a.bR=Dh;a.bo=Dh;a.br=null;a.bP=null;a.bz=null;a.bT=null;a.bv=0;a.bD=null;}
let BQ=null,F=null,BD=0,Bb=0,C$=null,Ex=a=>{let b,c,$$je,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:a:{try{try{Bb=Bb+1|0;Dk(a);a.bz=E1();$p=1;continue _;}catch($$e){$$je=G($$e);if($$je instanceof Bx){b=$$je;}else{throw $$e;}}C2(Dt(a),a,b);break a;}catch($$e){$$je=G($$e);b=$$je;}c=a.br;$p=2;continue _;}b=a.br;$p=4;continue _;case 1:a:{b:{c:{try{E9(a);if(T()){break _;}}catch($$e){$$je=G($$e);if($$je instanceof Bx){b=$$je;break c;}else{b=$$je;break b;}}b
=a.br;$p=3;continue _;}try{C2(Dt(a),a,b);break a;}catch($$e){$$je=G($$e);b=$$je;}}c=a.br;$p=2;continue _;}b=a.br;$p=4;continue _;case 2:BW(c);if(T()){break _;}a:{try{Co(c);Br(c);break a;}catch($$e){$$je=G($$e);b=$$je;}Br(c);S(b);}a.bv=0;Bb=Bb-1|0;a.bz=null;c=BQ;if(F!==c)F=c;F.bo=U();S(b);case 3:BW(b);if(T()){break _;}a:{try{Co(b);Br(b);break a;}catch($$e){$$je=G($$e);c=$$je;}Br(b);S(c);}a.bv=0;Bb=Bb-1|0;a.bz=null;b=BQ;if(F!==b)F=b;F.bo=U();return;case 4:BW(b);if(T()){break _;}a:{try{Co(b);Br(b);break a;}catch
($$e){$$je=G($$e);c=$$je;}Br(b);S(c);}a.bv=0;Bb=Bb-1|0;a.bz=null;b=BQ;if(F!==b)F=b;F.bo=U();return;default:Be();}}K().s(a,b,c,$p);},Dk=b=>{if(F!==b)F=b;F.bo=U();},E9=a=>{let b,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=a.bD;if(b===null)return;b=b;$p=1;case 1:DB(b);if(T()){break _;}return;default:Be();}}K().s(a,b,$p);},DA=()=>{return F;},DL=b=>{let $p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:Ei(b);if(T()){break _;}return;default:
Be();}}K().s(b,$p);},DM=(b,c)=>{let d,e;d=F;e=new CU;e.bW=d;e.bV=c;e.b2=Cb(e,DJ(b,Ba(2147483647))?2147483647:Bj(b));d.bP=e;},Dt=a=>{let b;b=a.b1;if(b!==null)return b;return C$;},Dz=()=>{let b,c,d;b=new Cm;c=null;b.br=new D;b.bv=1;b.bT=J(10);b.bD=c;d=BD;BD=d+1|0;b.bR=Ba(d);BQ=b;F=b;BD=1;Bb=1;C$=new C0;},Ei=b=>{let thread=Cy();let javaThread=CP();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback=function(){};callback.e=val=>
{thread.attribute=val;BK(javaThread);thread.resume();};callback.be=e=>{thread.attribute=Cs(e);BK(javaThread);thread.resume();};callback=De(callback);thread.suspend(()=>{try {DM(b,callback);;}catch($e){callback.be($e);}});return null;};
function Cf(){let a=this;D.call(a);a.bt=0;a.bB=0;a.bx=0;a.bw=0;a.bE=0;}
let Bi=E(Cf),CD=E(0),C0=E(),C2=(a,b,c)=>{c.bb();},D1=E(),BG=b=>{return Math.sin(b);},BO=b=>{return Math.cos(b);},CV=b=>{return Math.sqrt(b);},D_=()=>{return Math.random();},EY=(b,c)=>{return Math.min(b,c);},Bp=b=>{return Math.sign(b);},Bv=E(0);
function Ds(){D.call(this);this.bK=null;}
let EF=a=>{let b,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=a.bK;$p=1;case 1:Ex(b);if(T()){break _;}return;default:Be();}}K().s(a,b,$p);},D6=E(),U=()=>{return Bh((new Date()).getTime());};
function BN(){let a=this;D.call(a);a.bq=null;a.bI=null;a.bh=null;a.bk=0;}
let BP=E(R),Fb=E(),Ck=E(0),E6=E(0),CA=E(R);
function CB(){D.call(this);this.bJ=null;}
let Ew=a=>{D9(a.bJ);},E5=E(),Dq=E(),En=null,CK=null,BS=null,BJ=null,Cw=null,CI=null,CR=null,BA=()=>{BA=CO(Dq);DU();},DU=()=>{let b;En=new WeakMap();CK=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();BS=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();BJ=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(BS===null)b=null;else{b=new Cj;b=new FinalizationRegistry(V(!(b instanceof L)?b:b.bj,"accept"));}CI=b;if(BJ===null)b=null;else{b=new Ci;b=new FinalizationRegistry(V(!(b instanceof L)?b:b.bj,"accept"));}CR
=b;},Eq=E(),C8=E(0);
function CJ(){D.call(this);this.bu=null;}
let De=b=>{let c;c=new CJ;c.bu=b;return c;},DV=(a,b)=>{a.bu.e(b);},Fa=(a,b)=>{a.bu.be(b);};
function Dc(){let a=this;D.call(a);a.bN=null;a.bO=null;a.bL=0;a.bM=null;}
let DW=E(),Cd=E(0),Cj=E(),EN=(b,c)=>{b;BA();BS.delete(c);},Ci=E(),E0=(b,c)=>{b;BA();BJ.delete(c);},Cl=E(BU),Dn=E(0),CG=E(),Eb=a=>{return;},Du=()=>{let a=new CG();Eb(a);return a;},D0=(a,b)=>{return;},Bf=(a,b)=>{let c;if(b>0)return D_()*b|0;c=new Cv;X(c);c.bn=1;c.bm=1;S(c);};
function Do(){let a=this;D.call(a);a.b5=null;a.by=null;a.bU=null;a.bH=null;a.bS=null;a.bQ=null;}
let EG=(a,b,c,d)=>{let e,f,g,h,i,j,k;e=Bo(2);f=e.data;a.b5=e;f[0]=b;f[1]=c;g=window.document.createElement("canvas");a.by=g;h=b;g.width=h;i=a.by;g=c;i.height=g;g=a.by.getContext("2d");a.bU=g;j=b;k=c;h=g.createImageData(j,k);a.bH=h;g=new CE;g.bG=Bo(M(b,c));g.b0=h;a.bS=g;h=new Cx;h.bY=g;a.bQ=h;},DC=(a,b,c)=>{let d=new Do();EG(d,a,b,c);return d;},D4=a=>{return a.bQ;},DQ=a=>{let b,c,d,e,f,g,h,i,j;b=a.bH.data;c=a.bS.bG;d=0;e=0;while(true){f=c.data;if(d>=f.length)break;g=f[d];h=g>>16&255;b[e]=h;h=e+1|0;i=g>>8&255;b[h]
=i;h=e+2|0;g=g&255;b[h]=g;b[e+3|0]=255;d=d+1|0;e=e+4|0;}j=a.bU;b=a.bH;j.putImageData(b,0.0,0.0);};
function CE(){let a=this;D.call(a);a.bG=null;a.b0=null;}
let EC=a=>{return a.bG;};
function Cx(){D.call(this);this.bY=null;}
let Ep=a=>{return a.bY;},E$=E(),CL=E(0);
function CU(){let a=this;D.call(a);a.bW=null;a.bV=null;a.b6=0;a.b2=0;}
let Dx=a=>{let b,c;if(!a.b6){b=a.bW;b.bP=null;if(F!==b)F=b;F.bo=U();c=a.bV;b=null;c.bu.e(b);}},Cv=E(R);
Dy([]);
CW([D,0,0,[],0,3,0,0,0,Ct,0,D,[],3,3,0,0,0,CN,0,D,[],3,3,0,0,0,CM,0,D,[Ct,CN],4,3,0,0,0,Ea,0,D,[],4,3,0,0,0,EJ,0,D,[],4,3,0,0,0,Bx,0,D,[],0,3,0,0,0,I,0,Bx,[],0,3,0,0,0,R,0,I,[],0,3,0,0,0,E3,0,R,[],0,3,0,0,0,By,0,D,[],3,3,0,0,0,BT,0,D,[],3,3,0,0,0,Cc,0,D,[],3,3,0,0,0,O,0,D,[By,BT,Cc],0,3,0,0,0,B0,0,D,[By],1,3,0,0,0,Et,0,B0,[BT],0,3,0,0,0,Cg,0,D,[By,Cc],0,0,0,0,0,Dr,0,D,[],3,3,0,0,0,C1,0,Cg,[Dr],0,3,0,0,0,D2,0,D,[],0,3,0,0,0,Er,0,D,[],0,3,0,0,0,Em,0,D,[],0,3,0,0,0,Dd,0,D,[],0,3,0,P,0,EU,0,D,[],4,3,0,0,0,DT,0,
D,[],0,3,0,0,0,DO,0,D,[],0,3,0,0,0,B2,0,D,[],0,3,0,0,0,Cr,0,D,[],3,3,0,0,0,Dg,0,B2,[Cr],0,3,0,0,0,Bm,0,D,[],3,3,0,0,0,Z,0,D,[Bm],3,3,0,0,0,B$,0,D,[Z],0,3,0,0,0,L,0,D,[],4,3,0,0,0,B8,0,D,[Z],0,3,0,0,0,B9,0,D,[Z],0,3,0,0,0,B6,0,D,[Z],0,3,0,0,0,B7,0,D,[Z],0,3,0,0,0,B4,0,D,[Z],0,3,0,0,0,B5,0,D,[Z],0,3,0,0,0,B_,0,D,[Z],0,3,0,0,0,Ca,0,D,[Z],0,3,0,0,0,Da,0,D,[],3,3,0,0,0,BV,0,D,[Da],0,3,0,0,0,Cn,0,D,[BT],0,3,0,0,0,DD,0,D,[],4,3,0,0,0,Dp,0,D,[],0,3,0,0,0,BU,0,R,[],0,3,0,0,0,Cm,0,D,[Cr],0,3,0,0,0,Cf,0,D,[],0,3,0,0,0,Bi,
0,Cf,[],0,3,0,0,0]);
CW([CD,0,D,[],3,3,0,0,0,C0,0,D,[CD],0,3,0,0,0,D1,0,D,[],4,3,0,0,0,Bv,0,D,[],3,3,0,0,0,Ds,0,D,[Bv],0,3,0,0,["o",B3(EF)],D6,0,D,[],4,3,0,0,0,BN,0,D,[],0,0,0,0,0,BP,0,R,[],0,3,0,0,0,Fb,0,D,[Bm],1,3,0,0,0,Ck,0,D,[],3,3,0,0,0,E6,0,D,[Bv,Ck],3,0,0,0,0,CA,0,R,[],0,3,0,0,0,CB,0,D,[Bv],0,3,0,0,["o",B3(Ew)],E5,0,D,[],4,3,0,0,0,Dq,0,D,[],0,0,0,BA,0,Eq,0,D,[Bm],0,3,0,0,0,C8,0,D,[],3,3,0,0,0,CJ,0,D,[C8],0,0,0,0,["e",CT(DV),"be",CT(Fa)],Dc,0,D,[Bv],0,3,0,0,0,DW,0,D,[Bm],1,3,0,0,0,Cd,0,D,[Bm],3,0,0,0,0,Cj,0,D,[Cd],0,3,0,0,
0,Ci,0,D,[Cd],0,3,0,0,0,Cl,0,BU,[],0,3,0,0,0,Dn,0,D,[],3,3,0,0,0,CG,0,D,[Dn,By],0,3,0,0,0,Do,0,D,[],0,3,0,0,0,CE,0,D,[],0,3,0,0,0,Cx,0,D,[],0,3,0,0,0,E$,0,D,[],0,3,0,0,0,CL,0,D,[],3,3,0,0,0,CU,0,D,[Bv,Ck,CL],0,0,0,0,["o",B3(Dx)],Cv,0,R,[],0,3,0,0,0]);
let D$=BB(EV),EB=BB(BX),Df=BB(Cq);
Eu(["Can\'t enter monitor from another thread synchronously","<java_object>@","null","game_frame","0","object","function","string","number","undefined","main"]);
O.prototype.toString=function(){return BM(this);};
O.prototype.valueOf=O.prototype.toString;D.prototype.toString=function(){return BM(EL(this));};
D.prototype.__teavm_class__=function(){return ED(this);};
let C=DG(Eg);
C.javaException=DN;
let Fi=Symbol('jsoClass');
(()=>{let c;c=B$.prototype;c.handleEvent=W(ER);c=B8.prototype;c.handleEvent=W(DX);c=B9.prototype;c.handleEvent=W(D5);c=B6.prototype;c.handleEvent=W(Ev);c=B7.prototype;c.handleEvent=W(E4);c=B4.prototype;c.handleEvent=W(EA);c=B5.prototype;c.handleEvent=W(Dv);c=B_.prototype;c.handleEvent=W(Ef);c=Ca.prototype;c.handleEvent=W(DK);c=Cj.prototype;c.accept=W(EN);c=Ci.prototype;c.accept=W(E0);})();
B.main=C;}));