"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let Da=2463534242,Ef=()=>{let x=Da;x^=x<<13;x^=x>>>17;x^=x<<5;Da=x;return x;},B1=f=>function(){return f(this);},CS=f=>function(p1){return f(this,p1);},DG=f=>function(){let args=Array.prototype.slice.apply(arguments);C8(function()
{f.apply(this,args);});},DE=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=BK(Bc(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Bl(args[i]);}C8(()=>{f.call(null,javaArgs);},callback);},CN=target=>target.$clinit=()=>{},EF=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName
+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=Bc();}return function(){superclass.call(this);};},BG=cls=>Ek(cls),Bc=()=>D,CO=()=>{{return Dy();}},BI=t=>{{return Dj(t);}},W=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},EM=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},BJ=(name,binaryName)=>{let cls=EM();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName
=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},EX=BJ("boolean","Z"),BW=BJ("char","C"),Cp=BJ("int","I"),Eb=BJ("double","D"),Y=(a,b)=>a>b?1:a<b? -1:a===b?0:1,M=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Dg=BigInt(0),Ba=val=>BigInt.asIntN(64,BigInt(val|0)),Bh=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),Bj
=val=>Number(BigInt.asIntN(32,val))|0,Ct=(a,b)=>a>b,DH=(a,b)=>a>=b,C3=(a,b)=>BigInt.asIntN(64,a+b),CW=(a,b)=>BigInt.asIntN(64,a -b),BK=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bs(cls))(data);},BA=sz=>new ED(new Uint16Array(sz)),Bo=sz=>new De(new Int32Array(sz)),BN=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new De(buffer);},EQ=sz=>new D$(new Int8Array(sz)),DM=sz=>new Er(new Float64Array(sz)),Bs=cls=>{let result=cls.$array;if(result===null){function JavaArray(data)
{(Bc()).call(this);this.data=data;}JavaArray.prototype=Object.create((Bc()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.b7=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]
=this.data[i];}}return new (Bs(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[Bc()],primitive:false,superclass:Bc(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},Cg,Ew=strings=>{E$();Cg=new Array(strings.length);for(let i=0;i<strings.length;++i){Cg[i]=C4(Bl(strings[i]));}},J=index=>Cg[index],Cd=(array,offset,count)=>
{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bl=str=>str===null?null:D6(str),BL=str=>str===null?null:str.bf,E$=()=>(()=>{})(),C4;
{C4=str=>str;}let S=ex=>{throw Cr(ex);},Bw=Symbol("javaException"),Cr=ex=>{if(!ex.$jsException){X(ex);}return ex.$jsException;},X=ex=>{let javaCause=E4(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Bd("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bw]=ex;ex.$jsException=err;CX(err,ex);},CX=(err,ex)=>{if(typeof D2==="function"&&err.stack){let stack=D2(err.stack);let javaStack
=BK(Ep(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=EB(Bl(element.className),Bl(element.methodName),Bl(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){EU(ex,javaStack);}}},Bd;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Bd=function Bd(message,cause){let self=Reflect.construct(Error,[void 0,cause],Bd);Object.setPrototypeOf(self,Bd.prototype);self[defaultMessage]=message;return self;}
;Bd.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Bd},message:{get(){try {let javaException=this[Bw];if(typeof javaException==='object'){let javaMessage=Du(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Bd=Error;}let DL=e=>e instanceof Error&&typeof e[Bw]==='object'?e[Bw]:null,H=err=>
{let ex=err[Bw];if(!ex){ex=DX(Bl("(JavaScript) "+err.toString()));err[Bw]=ex;ex.$jsException=err;CX(err,ex);}return ex;},DX=message=>Em(message),Du=t=>EY(t),E4=t=>E9(t),Ep=()=>Bc(),EB=(className,methodName,fileName,lineNumber)=>{{return null;}},EU=(e,stack)=>{},CP=null,Dw=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}CP=packages;},CV=data=>{let packages=CP;let i=
0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags
&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit
=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}};
function Q(runner){this.status=3;this.stack=[];this.suspendCallback=null;this.runner=runner;this.attribute=null;this.completeCallback=null;}
Q.prototype.push=function(){for(let i=0;i<arguments.length;++i){this.stack.push(arguments[i]);}return this;};Q.prototype.s=Q.prototype.push;Q.prototype.pop=function(){return this.stack.pop();};Q.prototype.l=Q.prototype.pop;Q.prototype.isResuming=function(){return this.status===2;};Q.prototype.isSuspending=function(){return this.status===1;};Q.prototype.suspend=function(callback){this.suspendCallback=callback;this.status=1;};Q.prototype.start=function(callback){if(this.status!==3){throw new Error("Thread already started");}if
(BE!==null){throw new Error("Another thread is running");}this.status=0;this.completeCallback=callback?callback:result=>{if(result instanceof Error){throw result;}};this.run();};Q.prototype.resume=function(){if(BE!==null){throw new Error("Another thread is running");}this.status=2;this.run();};Q.prototype.run=function(){BE=this;let result;try {result=this.runner();}catch(e){result=e;}finally {BE=null;}if(this.suspendCallback!==null){let self=this;let callback=this.suspendCallback;this.suspendCallback=null;callback(()=>
self.resume());}else if(this.status===0){this.completeCallback(result);}};let T=()=>{let thread=K();return thread!=null&&thread.isSuspending();},Bg=()=>{let thread=K();return thread!=null&&thread.isResuming();},Cx=()=>{let nativeThread=K();if(nativeThread===null){throw new Error("Suspension point reached from non-threading context "+"(perhaps, from native JS method). See https://teavm.org/docs/runtime/coroutines.html "+"('Interaction with JavaScript' section)");}return nativeThread;},C8=(runner,callback)=>(new Q(runner)).start(callback),BE
=null,K=()=>BE,Be=()=>{throw new Error("Invalid recorded state");};
function D(){this.bh=null;this.$id$=0;}
let Fk=b=>{let c,d;c=F;if(c===null)return;if(b.bh===null){d=new BM;d.bg=c;b.bh=d;}b=b.bh;d=b.bg;if(d===null)b.bg=c;else if(d!==c){d=new Cz;X(d);d.bm=1;d.bl=1;d.bE=J(0);S(d);}b.bj=b.bj+1|0;},Fe=b=>{let c,d;if(F===null)return;if(!BD(b)){c=b.bh;if(c.bg===F){d=c.bj-1|0;c.bj=d;if(!d)c.bg=null;BD(b);return;}}b=new BP;X(b);b.bm=1;b.bl=1;S(b);},BV=b=>{let c,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:c=1;$p=1;case 1:EJ(b,c);if(T()){break _;}return;default:Be();}}K().s(b,
c,$p);},EJ=(b,c)=>{let d,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:if(b.bh===null){d=new BM;d.bg=F;b.bh=d;}d=b.bh;if(d.bg===null)d.bg=F;if(d.bg===F){d.bj=d.bj+c|0;return;}$p=1;case 1:DC(b,c);if(T()){break _;}return;default:Be();}}K().s(b,c,d,$p);},Eu=(b,c,d)=>{let e,f,g;e=F;f=b.bh;if(f===null){f=new BM;f.bg=e;b.bh=f;if(e!==e)F=e;F.bn=U();b=b.bh;b.bj=b.bj+c|0;b=null;d.bt.e(b);return;}if(f.bg===null){f.bg=e;if(e!==e)F=e;F.bn=U();b=b.bh;b.bj=b.bj+c|0;b
=null;d.bt.e(b);return;}if(f.bp===null)f.bp=DN();f=f.bp;g=new Db;g.bM=e;g.bN=b;g.bK=c;g.bL=d;d=g;f.push(d);},Bq=b=>{EK(b,1);},EK=(b,c)=>{let d;if(!BD(b)){d=b.bh;if(d.bg===F){c=d.bj-c|0;d.bj=c;if(c>0)return;d.bg=null;d=d.bp;if(d!==null&&!(d.length?0:1)){d=new CB;d.bI=b;B_(d,0);}else BD(b);return;}}b=new BP;X(b);b.bm=1;b.bl=1;S(b);},D9=b=>{let c,d,e;if(!BD(b)){c=b.bh;if(c.bg===null){b=c.bp;if(b!==null&&!(b.length?0:1)){b=c.bp.shift();if(b!==null&&!(b instanceof Bc()))b=CC(b);d=b;c.bp=null;b=d;c=b.bM;d=b.bN;e=
b.bK;b=b.bL;if(F!==c)F=c;F.bn=U();d=d.bh;d.bg=c;d.bj=d.bj+e|0;c=null;b.bt.e(c);}return;}}},BD=a=>{let b,c;b=a.bh;if(b===null)return 1;a:{if(b.bg===null){c=b.bp;if(!(c!==null&&!(c.length?0:1))){b=b.bH;if(b===null)break a;if(b.length?0:1)break a;}}return 0;}a.bh=null;return 1;},El=a=>{return;},E3=()=>{let a=new D();El(a);return a;},EN=a=>{let b,c,d,e,f,g,h,i,j;b=a;if(!b.$id$)b.$id$=Ef();c=Ei(a.$id$,4);b=new CZ;b.br=BA(16);d=b.bo;e=b;f=J(1);e=e;Cy(e,d,f);Cy(e,b.bo,c===null?J(2):c);f=new O;g=b.br;h=g.data;i=b.bo;j
=h.length;if(i>=0&&i<=(j-0|0)){f.bf=Cd(g.data,0,i);return f;}b=new BT;D8(b);b.bm=1;b.bl=1;ET(b);S(b);},Cn=a=>{let b,c;b=a.bh;if(!(b!==null&&b.bg===F?1:0)){b=new BP;X(b);b.bm=1;b.bl=1;S(b);}b=b.bH;if(b===null)return;while(!(b.length?0:1)){c=b.shift();if(c!==null&&!(c instanceof Bc()))c=CC(c);c=c;if(!c.n())B_(c,0);}a.bh.bH=null;},DC=(b,c)=>{let thread=Cx();let javaThread=CO();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback
=function(){};callback.e=val=>{thread.attribute=val;BI(javaThread);thread.resume();};callback.bd=e=>{thread.attribute=Cr(e);BI(javaThread);thread.resume();};callback=Dd(callback);thread.suspend(()=>{try {Eu(b,c,callback);;}catch($e){callback.bd($e);}});return null;},Cs=E(0),CM=E(0);
function CL(){D.call(this);this.b6=null;}
let Ek=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new CL;c.b6=b;b.classObject=c;}return c;},Ea=E(),V=(b,c)=>{let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},EL=E(),Fb=b=>{setTimeout(()=>{DG(Dk)(b);},0);},Dk=b=>{let $p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:b.o();if(T()){break _;}return;default:Be();}}K().s(b,
$p);},B_=(b,c)=>{setTimeout(()=>{Dk(b);},c);},DN=()=>{return [];};
function By(){let a=this;D.call(a);a.bE=null;a.b2=null;a.bm=0;a.bl=0;}
let ET=a=>{return a;},D8=a=>{X(a);},EY=a=>{return a.bE;},E9=a=>{let b;b=a.b2;if(b===a)b=null;return b;},I=E(By),R=E(I),DQ=(a,b)=>{X(a);a.bm=1;a.bl=1;a.bE=b;},Em=a=>{let b=new R();DQ(b,a);return b;},E5=E(R),Bz=E(0),BS=E(0),Ca=E(0),O=E(),CF=null,C$=null,C1=null,DF=(a,b)=>{a.bf=Cd(b.data,0,b.data.length);},Ff=a=>{let b=new O();DF(b,a);return b;},Ee=(a,b)=>{a.bf=b;},D6=a=>{let b=new O();Ee(b,a);return b;},Fi=()=>{let b;CF=BA(0);b=new O;b.bf="";C$=b;C1=new BU;},BZ=E(),Ev=E(BZ),C6=null,ER=b=>{let c,d;if(!b)return 32;c
=0;d=b>>>16|0;if(d)c=16;else d=b;b=d>>>8|0;if(!b)b=d;else c=c|8;d=b>>>4|0;if(!d)d=b;else c=c|4;b=d>>>2|0;if(!b)b=d;else c=c|2;if(b>>>1|0)c=c|1;return (32-c|0)-1|0;},Fh=()=>{C6=BG(Cp);};
function Cf(){let a=this;D.call(a);a.br=null;a.bo=0;}
let Cy=(a,b,c)=>{let d,e,f,g;if(b>=0&&b<=a.bo){if(c===null)c=J(2);else if(c.bf.length?0:1)return a;d=a.bo+c.bf.length|0;DR(a,d);e=a.bo-1|0;while(e>=b){a.br.data[e+c.bf.length|0]=a.br.data[e];e=e+(-1)|0;}a.bo=a.bo+c.bf.length|0;e=0;a:{while(e<c.bf.length){f=a.br;g=b+1|0;if(e<0)break a;if(e>=c.bf.length)break a;f.data[b]=c.bf.charCodeAt(e);e=e+1|0;b=g;}return a;}c=new Ck;X(c);c.bm=1;c.bl=1;S(c);}c=new Ck;X(c);c.bm=1;c.bl=1;S(c);},DR=(a,b)=>{let c,d,e,f,g,h;c=a.br.data;d=c.length;if(d>=b)return;if(d>=1073741823)e
=2147483647;else{f=d*2|0;e=5;if(f>e)e=f;if(b>e)e=b;}g=BA(e);if(e<d)d=e;h=g.data;b=0;while(b<d){h[b]=c[b];b=b+1|0;}a.br=g;},Dp=E(0),CZ=E(Cf),D1=E(),Et=E(),En=E(),Dc=E(),Bk=null,Bu=null,Bx=null,G=null,C2=null,N=null,Co=0,BY=null,P=()=>{P=CN(Dc);EZ();},Eh=b=>{let c,d,e,f,g,h,i,j;P();c=window;Bu=c;d=c.document;Bx=d;c=d.getElementById(BL(BY));b=Bo(2);e=b.data;N=b;b=Bm.data;e[0]=b[0];e[1]=b[1];if(c===null)G=Dh(Bx.body);else if(!(c instanceof HTMLCanvasElement?1:0)){c.removeAttribute("id");G=Dh(c);if(c.hasAttribute("fullscreen")
?1:0){c.removeAttribute("fullscreen");G.setAttribute("fullscreen","");}}else{G=c;b=(CA(c)).data;if(b[0])N.data[0]=G.width;else G.width=N.data[0];if(b[1])N.data[1]=G.height;else G.height=N.data[1];}C2=G.getContext("2d");if(!(G.hasAttribute("fullscreen")?1:0))CR();else{G.removeAttribute("fullscreen");N.data[0]=Bu.innerWidth;N.data[1]=Bu.innerHeight;G.width=N.data[0];G.height=N.data[1];Bx.body.setAttribute("style","margin:0;overflow:hidden;height:100vh;width:100vw;");Co=1;f=G.hasAttribute("fullscreen-alt")?1:0;Cb
=f;if(f)G.removeAttribute("fullscreen-alt");}c=new Df;d=G;g=C2;c.b3=d;c.bY=g;h=new Dn;h.bx=g;h.bB=d;c.bW=h;c.bk=Bo(32767);Bk=c;d=new Cl;g=null;d.bq=new D;d.bu=1;d.bS=g;d.bC=c;i=BC;BC=i+1|0;d.bQ=Ba(i);c=new Dq;c.bJ=d;Fb(c);G.tabIndex=0;G.setAttribute("style","outline:none;border:none;image-rendering:pixelated;");G.focus();c=G;g=new B8;h="addEventListener";d="mousedown";j=!(g instanceof L)?g:g.bi;c[h](d,V(j,"handleEvent"));c=G;g=new B6;h="addEventListener";d="mouseup";j=!(g instanceof L)?g:g.bi;c[h](d,V(j,"handleEvent"));c
=G;g=new B7;h="addEventListener";d="mousemove";j=!(g instanceof L)?g:g.bi;c[h](d,V(j,"handleEvent"));c=G;g=new B4;h="addEventListener";d="mouseleave";j=!(g instanceof L)?g:g.bi;c[h](d,V(j,"handleEvent"));c=G;g=new B5;h="addEventListener";d="contextmenu";j=!(g instanceof L)?g:g.bi;c[h](d,V(j,"handleEvent"));c=G;g=new B2;h="addEventListener";d="keydown";j=!(g instanceof L)?g:g.bi;c[h](d,V(j,"handleEvent"));c=G;g=new B3;h="addEventListener";d="keyup";j=!(g instanceof L)?g:g.bi;c[h](d,V(j,"handleEvent"));c=Bu;g
=new B9;h="addEventListener";d="resize";j=!(g instanceof L)?g:g.bi;c[h](d,V(j,"handleEvent"));c=Bx;g=new B$;c.addEventListener("click",V(!(g instanceof L)?g:g.bi,"handleEvent"));},Dh=b=>{let c,d;P();c=Bx.createElement("canvas");d=BL(BY);c.id=d;d=N.data[0];c.width=d;d=N.data[1];c.height=d;b.appendChild(c);return c;},CR=()=>{let b,c,d;P();b=CA(G);c=Bu.innerWidth;d=Bu.innerHeight;if(!(!Co&&b.data[0]&&c>=N.data[0])){G.width=c;N.data[0]=c;}if(!(!Co&&b.data[1]&&d>=N.data[1])){G.height=d;N.data[1]=d;}},DD=b=>{let c,
d;P();c=G;d=(BX(c.width,c.height,b.offsetX,b.offsetY)).data;c=new Bi;c.bs=502;c.bw=d[0];c.bv=d[1];c.bD=b.button!=2?0:4;Bt(Bk,c);b.preventDefault();},EG=b=>{let c,d;P();c=G;d=(BX(c.width,c.height,b.offsetX,b.offsetY)).data;c=new Bi;c.bs=501;c.bw=d[0];c.bv=d[1];c.bD=b.button!=2?0:4;Bt(Bk,c);b.preventDefault();},EZ=()=>{let b;CF=BA(0);b=new O;b.bf="";C$=b;C1=new BU;C6=BG(Cp);DO();C5=BG(BW);Di=BK(Cm,128);Dx();BY=J(3);},EV=E(),Ei=(b,c)=>{let d,e,f,g,h,i,j,k,l;if(!b)return J(4);d=1<<c;e=d-1|0;f=(((32-ER(b)|0)+c|0)
-1|0)/c|0;g=BA(f);h=g.data;i=M(f-1|0,c);j=0;while(i>=0){k=j+1|0;h[j]=DY((b>>>i|0)&e,d);i=i-c|0;j=k;}l=new O;l.bf=Cd(g.data,0,h.length);return l;},DS=E(),Br=null,Bm=null,Cb=0,BX=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o;f=Br.data;g=b/f[0]|0;h=c/f[1]|0;if(g<h)h=g;i=h;j=f[0]*i;h=Bj(Bh(j+Bp(j)*0.5));i=Br.data[1]*i;g=Bj(Bh(i+Bp(i)*0.5));k=(b-h|0)/2|0;l=(c-g|0)/2|0;if(d>=k&&d<(k+h|0)&&e>=l&&e<(l+g|0)){j=(d-k|0)/h;m=(e-l|0)/g;i=j*Bm.data[0];n=Bj(Bh(i+Bp(i)*0.5));i=m*Bm.data[1];o=Bj(Bh(i+Bp(i)*0.5));if(n<0)n=0;else{f=Bm.data;if
(n>(f[0]-1|0))n=f[0]-1|0;}if(o<0)o=0;else{f=Bm.data;if(o>f[1])o=f[1]-1|0;}return BN([n,o]);}return BN([(-1),(-1)]);},DO=()=>{Br=BN([214,120]);Bm=BN([856,480]);Cb=0;};
function B0(){let a=this;D.call(a);a.b3=null;a.bY=null;a.bW=null;}
let EA=a=>{return 1;},EO=a=>{return a.bW;},Cq=E(0);
function Df(){B0.call(this);this.bk=null;}
let Dz=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv,bw,bx,by,bz,bA,bB,bC,bD,bE,bF,bG,bH,bI,bJ,bK,bL,bM,bN,bO,bP,bQ,bR,bS,bT,bU,bV,bW,bX,bY,bZ,b0,b1,b2,b3,b4,b5,$$je,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b5=$T.l();b4=$T.l();b3=$T.l();b2=$T.l();b1=$T.l();b0=$T.l();bZ=$T.l();bY=$T.l();bX=$T.l();bW=$T.l();bV=$T.l();bU=$T.l();bT=$T.l();bS=$T.l();bR=$T.l();bQ=$T.l();bP=$T.l();bO=$T.l();bN=$T.l();bM=$T.l();bL=$T.l();bK=$T.l();bJ=$T.l();bI
=$T.l();bH=$T.l();bG=$T.l();bF=$T.l();bE=$T.l();bD=$T.l();bC=$T.l();bB=$T.l();bA=$T.l();bz=$T.l();by=$T.l();bx=$T.l();bw=$T.l();bv=$T.l();bu=$T.l();bt=$T.l();bs=$T.l();br=$T.l();bq=$T.l();bp=$T.l();bo=$T.l();bn=$T.l();bm=$T.l();bl=$T.l();bk=$T.l();bj=$T.l();bi=$T.l();bh=$T.l();bg=$T.l();bf=$T.l();be=$T.l();bd=$T.l();bc=$T.l();bb=$T.l();ba=$T.l();z=$T.l();y=$T.l();x=$T.l();w=$T.l();v=$T.l();u=$T.l();t=$T.l();s=$T.l();r=$T.l();q=$T.l();p=$T.l();o=$T.l();n=$T.l();m=$T.l();l=$T.l();k=$T.l();j=$T.l();i=$T.l();h=
$T.l();g=$T.l();f=$T.l();e=$T.l();d=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:a:{try{b=Ds();c=DA(214,120,1);d=EE(Eq(D3(c)));e=Bo(262144);DZ(b,Ba(18295169));f=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}g=e.data;while(true){try{if(f>=262144)break;g[f]=((f/64|0)%64|0)<=(32+Bf(b,8)|0)?0:Bf(b,8)+1|0;f=f+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{h=Bo(12288);i=1;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}
else{throw $$e;}}e=h.data;while(true){try{if(i>=16)break;j=255-Bf(b,96)|0;k=0;while(k<48){l=0;while(l<16){m=9858122;n=Y(i,4);if(!n)m=8355711;if(!(!n&&Bf(b,3)))j=255-Bf(b,96)|0;n=Y(i,1);if(!n&&k<((((M(l,l)*3|0)+(l*81|0)|0)>>2&3)+18|0))m=6990400;else if(!n&&k<((((M(l,l)*3|0)+(l*81|0)|0)>>2&3)+19|0))j=(j*2|0)/3|0;b:{if(i==7){c:{m=6771249;if(l>0&&l<15){if(k>0&&k<15)break c;if(k>32&&k<47)break c;}if(Bf(b,2))break b;j=M(j,150-((l&1)*100|0)|0)/100|0;break b;}m=12359778;o=l-7|0;p=(k&15)-7|0;if(o<0)o=1-o|0;if(p<0)p=
1-p|0;if(p<=o)p=o;j=(196-Bf(b,32)|0)+((p%3|0)*32|0)|0;}}if(i==5){m=11876885;if(!(((l+((k/4|0)*4|0)|0)%8|0)&&(k%4|0)))m=12365733;}n=k<32?j:j/2|0;if(i==8){m=5298487;if(!Bf(b,2)){m=0;n=255;}}n=(M(m>>16&255,n)/255|0)<<16|(M(m>>8&255,n)/255|0)<<8|(M(m&255,n)/255|0);e[(l+(k*16|0)|0)+((i*256|0)*3|0)|0]=n;l=l+1|0;}k=k+1|0;}i=i+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{q=96.5;r=65.0;s=96.5;t=0.0;u=0.0;v=0.0;w=U();x=0;y=0.0;z=0.0;ba=y;bb=BF(ba);bc=BO(ba);ba=z;bd=BF(ba);be
=BO(ba);while(Ct(CW(U(),w),Ba(10))){h=a.bk.data;if(h[2]>0){bf=(h[2]-428|0)/214.0*2.0;bg=(h[3]-240|0)/120.0*2.0;bh=CU(bf*bf+bg*bg)-1.2000000476837158;if(bh<0.0)bh=0.0;if(bh>0.0){y=y+bf*bh/400.0;z=z-bg*bh/400.0;if(z<(-1.5700000524520874))z=(-1.5700000524520874);if(z>1.5700000524520874)z=1.5700000524520874;}}w=C3(w,Ba(10));h=a.bk.data;bf=0.0+(h[119]-h[115]|0)*0.019999999552965164;bg=0.0+(h[100]-h[97]|0)*0.019999999552965164;bh=t*0.5;bi=u*0.9900000095367432;bj=v*0.5;t=bh+bb*bf+bc*bg;v=bj+bc*bf-bb*bg;u=bi+0.003000000026077032;bk
=0;while(bk<3){bl=q+t*(((bk+0|0)%3|0)/2|0);bm=bk+1|0;bn=r+u*((bm%3|0)/2|0);bo=s+v*(((bk+2|0)%3|0)/2|0);bp=0;d:{e:{while(bp<12){bq=(bl+(bp>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;br=(bn+((bp>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bs=(bo+(bp>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bq<0)break e;if(br<0)break e;if(bs<0)break e;if(bq>=64)break e;if(br>=64)break e;if(bs>=64)break e;if(g[(bq+(br*64|0)|0)+(bs*4096|0)|0]>0)break e;bp=bp+1|0;}break d;}if(bk!=1){bl=q;bn=r;bo
=s;}else if(h[32]>0&&u>0.0){h[32]=0;u=(-0.10000000149011612);bl=q;bn=r;bo=s;}else{u=0.0;bl=q;bn=r;bo=s;}}bk=bm;q=bl;r=bn;s=bo;}}h=a.bk.data;if(h[1]>0&&(-1)>0){g[(-1)]=0;h[1]=0;}if(h[0]>0&&(-1)>0){g[(-1)+x|0]=1;h[0]=0;}bt=0;while(bt<12){bu=(q+(bt>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bv=(r+((bt>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bw=(s+(bt>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bu>=0&&bv>=0&&bw>=0&&bu<64&&bv<64&&bw<64)g[(bu+(bv*64|0)|0)+(bw*4096|0)|0]=0;bt=bt
+1|0;}bx=(-1);by=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}bh=1.0*be;bl=1.0*bd;while(true){try{if(by>=214)break;bz=(by-107|0)/90.0;bA=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}bn=bz*bc;bB=bz*bb;while(true){try{if(bA>=120)break;bC=(bA-60|0)/90.0;bD=bh+bC*bd;bE=bC*be-bl;bF=bn+bD*bb;bG=bD*bc-bB;bH=0;bI=255;bJ=20.0;bK=5.0;bL=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}while(true){try{if(bL>=3)break;n=Y(bL,1);bf=n?bF:bE;l
=Y(bL,2);if(!l)bf=bG;k=Y(bf,0.0);if(k<0)bf= -bf;bM=1.0/bf;bN=bF*bM;bi=bE*bM;bj=bG*bM;bO=q-(q|0);if(!n)bO=r-(r|0);if(!l)bO=s-(s|0);if(k>0)bO=1.0-bO;bP=bM*bO;bQ=q+bN*bO;bR=r+bi*bO;bS=s+bj*bO;if(k<0){if(!bL)bQ=bQ-1.0;if(!n)bR=bR-1.0;if(!l)bS=bS-1.0;}}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}o=Y(bi,0.0);f:{try{while(true){ba=bP;if(ba>=bJ)break f;bT=(bQ|0)-64|0;bU=(bR|0)-64|0;bV=(bS|0)-64|0;if(bT<0)break f;if(bU<0)break f;if(bV<0)break f;if(bT>=64)break f;if(bU>=64)break f;if(bV>=64)break;bW
=(bT+(bU*64|0)|0)+(bV*4096|0)|0;bX=g[bW];if(bX>0){p=((bQ+bS)*16.0|0)&15;l=((bR*16.0|0)&15)+16|0;if(!n){p=(bQ*16.0|0)&15;l=(bS*16.0|0)&15;if(o<0)l=l+32|0;}g:{bY=16777215;if(bW==(-1)){if(p<=0)break g;j=l%16|0;if(j<=0)break g;if(p>=15)break g;if(j>=15)break g;}bY=e[(p+(l*16|0)|0)+((bX*256|0)*3|0)|0];}if(bP>=bK)bW=bx;else if(by!=(h[2]/4|0))bW=bx;else if(bA!=(h[3]/4|0))bW=bx;else{bZ=1;if(k>0)bZ=(-1);x=bZ<<(6*bL|0);bK=bP;}if(bY<=0)bx=bW;else{bI=M(255-(bP/20.0*255.0|0)|0,255-(((bL+2|0)%3|0)*50|0)|0)/255|0;bx=bW;bH
=bY;bJ=ba;}}bQ=bQ+bN;bR=bR+bi;bS=bS+bj;bP=bP+bM;}break f;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bL=bL+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b0=d.data;b1=M(bH>>16&255,bI)/255|0;b2=M(bH>>8&255,bI)/255|0;b3=M(bH&255,bI)/255|0;b0[by+(bA*214|0)|0]=b1<<16|b2<<8|b3;bA=bA+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{by=by+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}
else{throw $$e;}}}try{b4=Ba(2);$p=1;continue _;}catch($$e){$$je=H($$e);if($$je instanceof I){}else{throw $$e;}}}return;case 1:a:{h:{try{DJ(b4);if(T()){break _;}b=a;if(EA(b))break h;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}return;}try{E1(EO(b),c,0,0,856,480,null);b5=bx;ba=y;bb=BF(ba);bc=BO(ba);ba=z;bd=BF(ba);be=BO(ba);while(Ct(CW(U(),w),Ba(10))){h=a.bk.data;if(h[2]>0){bf=(h[2]-428|0)/214.0*2.0;bg=(h[3]-240|0)/120.0*2.0;bh=CU(bf*bf+bg*bg)-1.2000000476837158;if(bh<0.0)bh=0.0;if(bh
>0.0){y=y+bf*bh/400.0;z=z-bg*bh/400.0;if(z<(-1.5700000524520874))z=(-1.5700000524520874);if(z>1.5700000524520874)z=1.5700000524520874;}}w=C3(w,Ba(10));h=a.bk.data;bf=0.0+(h[119]-h[115]|0)*0.019999999552965164;bg=0.0+(h[100]-h[97]|0)*0.019999999552965164;bh=t*0.5;bi=u*0.9900000095367432;bj=v*0.5;t=bh+bb*bf+bc*bg;v=bj+bc*bf-bb*bg;u=bi+0.003000000026077032;bk=0;while(bk<3){bl=q+t*(((bk+0|0)%3|0)/2|0);bm=bk+1|0;bn=r+u*((bm%3|0)/2|0);bo=s+v*(((bk+2|0)%3|0)/2|0);bp=0;i:{j:{while(bp<12){bq=(bl+(bp>>0&1)*0.6000000238418579
-0.30000001192092896|0)-64|0;br=(bn+((bp>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bs=(bo+(bp>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bq<0)break j;if(br<0)break j;if(bs<0)break j;if(bq>=64)break j;if(br>=64)break j;if(bs>=64)break j;if(g[(bq+(br*64|0)|0)+(bs*4096|0)|0]>0)break j;bp=bp+1|0;}break i;}if(bk!=1){bl=q;bn=r;bo=s;}else if(h[32]>0&&u>0.0){h[32]=0;u=(-0.10000000149011612);bl=q;bn=r;bo=s;}else{u=0.0;bl=q;bn=r;bo=s;}}bk=bm;q=bl;r=bn;s=bo;}}h=a.bk.data;if(h[1]>0&&b5>0){g[b5]
=0;h[1]=0;}if(h[0]>0&&b5>0){g[b5+x|0]=1;h[0]=0;}bt=0;while(bt<12){bu=(q+(bt>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bv=(r+((bt>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bw=(s+(bt>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bu>=0&&bv>=0&&bw>=0&&bu<64&&bv<64&&bw<64)g[(bu+(bv*64|0)|0)+(bw*4096|0)|0]=0;bt=bt+1|0;}bx=(-1);by=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}bh=1.0*be;bl=1.0*bd;while(true){try{if(by>=214)break;bz=(by-107|0)/90.0;bA=0;}catch
($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}bn=bz*bc;bB=bz*bb;while(true){try{if(bA>=120)break;bC=(bA-60|0)/90.0;bD=bh+bC*bd;bE=bC*be-bl;bF=bn+bD*bb;bG=bD*bc-bB;bH=0;bI=255;bJ=20.0;bK=5.0;bL=0;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}while(true){try{if(bL>=3)break;n=Y(bL,1);bf=n?bF:bE;l=Y(bL,2);if(!l)bf=bG;k=Y(bf,0.0);if(k<0)bf= -bf;bM=1.0/bf;bN=bF*bM;bi=bE*bM;bj=bG*bM;bO=q-(q|0);if(!n)bO=r-(r|0);if(!l)bO=s-(s|0);if(k>0)bO=1.0-bO;bP=bM*bO;bQ=q+bN*bO;bR=r+
bi*bO;bS=s+bj*bO;if(k<0){if(!bL)bQ=bQ-1.0;if(!n)bR=bR-1.0;if(!l)bS=bS-1.0;}}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}o=Y(bi,0.0);k:{try{while(true){ba=bP;if(ba>=bJ)break k;bT=(bQ|0)-64|0;bU=(bR|0)-64|0;bV=(bS|0)-64|0;if(bT<0)break k;if(bU<0)break k;if(bV<0)break k;if(bT>=64)break k;if(bU>=64)break k;if(bV>=64)break;bW=(bT+(bU*64|0)|0)+(bV*4096|0)|0;bX=g[bW];if(bX>0){p=((bQ+bS)*16.0|0)&15;l=((bR*16.0|0)&15)+16|0;if(!n){p=(bQ*16.0|0)&15;l=(bS*16.0|0)&15;if(o<0)l=l+32|0;}l:{bY=16777215;if
(bW==b5){if(p<=0)break l;j=l%16|0;if(j<=0)break l;if(p>=15)break l;if(j>=15)break l;}bY=e[(p+(l*16|0)|0)+((bX*256|0)*3|0)|0];}if(bP>=bK)bW=bx;else if(by!=(h[2]/4|0))bW=bx;else if(bA!=(h[3]/4|0))bW=bx;else{bZ=1;if(k>0)bZ=(-1);x=bZ<<(6*bL|0);bK=bP;}if(bY<=0)bx=bW;else{bI=M(255-(bP/20.0*255.0|0)|0,255-(((bL+2|0)%3|0)*50|0)|0)/255|0;bx=bW;bH=bY;bJ=ba;}}bQ=bQ+bN;bR=bR+bi;bS=bS+bj;bP=bP+bM;}break k;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bL=bL+1|0;continue;}catch($$e){$$je=H($$e);if
($$je instanceof I){break a;}else{throw $$e;}}}try{b0=d.data;b1=M(bH>>16&255,bI)/255|0;b2=M(bH>>8&255,bI)/255|0;b3=M(bH&255,bI)/255|0;b0[by+(bA*214|0)|0]=b1<<16|b2<<8|b3;bA=bA+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{by=by+1|0;continue;}catch($$e){$$je=H($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b4=Ba(2);continue _;}catch($$e){$$je=H($$e);if($$je instanceof I){}else{throw $$e;}}}return;default:Be();}}K().s(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,
t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv,bw,bx,by,bz,bA,bB,bC,bD,bE,bF,bG,bH,bI,bJ,bK,bL,bM,bN,bO,bP,bQ,bR,bS,bT,bU,bV,bW,bX,bY,bZ,b0,b1,b2,b3,b4,b5,$p);},Bt=(a,b)=>{let c,d;a:{b:{c:{c=0;switch(b.bs){case 401:c=1;break c;case 501:c=1;d=a.bk.data;d[2]=b.bw;d[3]=b.bv;break b;case 503:case 506:d=a.bk.data;d[2]=b.bw;d[3]=b.bv;break a;case 505:break;case 402:break c;case 502:break b;default:break a;}a.bk.data[2]=0;break a;}a.bk.data[b.bA]=c;break a;}if((b.bD&4)<=0)a.bk.data[0]
=c;else a.bk.data[1]=c;}return 1;},Bn=E(0),Z=E(0),B8=E(),ES=(b,c)=>{b;EG(c);};
function L(){D.call(this);this.bi=null;}
let CC=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=Bl(typeof b);if(c===J(5))d=1;else if(!(J(5) instanceof O))d=0;else{e=J(5);d=c.bf!==e.bf?0:1;}a:{if(!d){if(c===J(6))d=1;else if(!(J(6) instanceof O))d=0;else{e=J(6);d=c.bf!==e.bf?0:1;}if(!d){d=0;break a;}}d=1;}BB();e=CJ;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bi=b;e.set(b,new WeakRef(h));return h;}if(c===J(7))d=1;else if(!(J(7) instanceof O))d=0;else{e=J(7);d=
c.bf!==e.bf?0:1;}if(d){i=BR;j=CH;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bi=b;k=h;i.set(b,new WeakRef(k));j.register(k,b);return h;}if(c===J(8))d=1;else if(!(J(8) instanceof O))d=0;else{e=J(8);d=c.bf!==e.bf?0:1;}if(d){l=BH;m=CQ;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bi=b;k=h;l.set(b,new WeakRef(k));m.register(k,b);return h;}if(c===J(9))d=1;else if(!(J(9) instanceof O))d=
0;else{e=J(9);d=c.bf!==e.bf?0:1;}if(d){f=Cv;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bi=b;Cv=new WeakRef(h);return h;}}e=new L;e.bi=b;return e;},B6=E(),DW=(b,c)=>{b;DD(c);},B7=E(),D4=(b,c)=>{let d;b;P();b=G;d=(BX(b.width,b.height,c.offsetX,c.offsetY)).data;b=new Bi;b.bs=503;b.bw=d[0];b.bv=d[1];Bt(Bk,b);},B4=E(),Ex=(b,c)=>{b;P();b=new Bi;b.bs=505;Bt(Bk,b);},B5=E(),E6=(b,c)=>{b;P();c.preventDefault();},B2=E(),EC=(b,c)=>{let d;b;P();b=new Bi;b.bs=401;d=c.keyCode;if(d>=65&&
d<=90)d=d+32|0;b.bA=d;Bt(Bk,b);c.preventDefault();},B3=E(),Dt=(b,c)=>{let d;b;P();b=new Bi;b.bs=402;d=c.keyCode;if(d>=65&&d<=90)d=d+32|0;b.bA=d;Bt(Bk,b);c.preventDefault();},B9=E(),Eg=(b,c)=>{b;P();CR();},B$=E(),DI=(b,c)=>{b;P();G.focus();},EW=E(),CA=b=>{let c,d;c=EQ(2);d=c.data;d[0]=0;d[1]=0;if(b.width)d[0]=1;if(b.height)d[1]=1;return c;},Ed=(b,c)=>{b.imageSmoothingEnabled=c;if(b.mozImageSmoothingEnabled!==undefined)b.mozImageSmoothingEnabled=c;if(b.webkitImageSmoothingEnabled!==undefined)b.webkitImageSmoothingEnabled
=c;if(b.msImageSmoothingEnabled!==undefined)b.msImageSmoothingEnabled=c;},C_=E(0),BU=E(),Cm=E(),C5=null,Di=null,DY=(b,c)=>{if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},Fg=()=>{C5=BG(BW);Di=BK(Cm,128);},DB=E();
function Dn(){let a=this;D.call(a);a.bx=null;a.bB=null;}
let E1=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o;h=Bm.data;if(e==h[0]&&f==h[1]){i=a.bB.width;j=a.bB.height;k=DM(2).data;l=i;h=Br.data;k[0]=l/h[0];m=j;k[1]=m/h[1];n=!Cb?D7(k[0],k[1]):E0(k[0],k[1]);o=Br.data[0]*n;e=Bj(Bh(o+Bp(o)*0.5));n=Br.data[1]*n;f=Bj(Bh(n+Bp(n)*0.5));c=(i-e|0)/2|0;d=(j-f|0)/2|0;a.bx.clearRect(0.0,0.0,l,m);}DP(b);Ed(a.bx,!!0);g=a.bx;b=b.by;m=c;l=d;n=e;o=f;g.drawImage(b,m,l,n,o);},BT=E(R);
function Cl(){let a=this;D.call(a);a.b0=null;a.bQ=Dg;a.bn=Dg;a.bq=null;a.bO=null;a.bz=null;a.bS=null;a.bu=0;a.bC=null;}
let BQ=null,F=null,BC=0,Bb=0,C9=null,Ez=a=>{let b,c,$$je,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:a:{try{try{Bb=Bb+1|0;Dj(a);a.bz=E3();$p=1;continue _;}catch($$e){$$je=H($$e);if($$je instanceof By){b=$$je;}else{throw $$e;}}C0(Dr(a),a,b);break a;}catch($$e){$$je=H($$e);b=$$je;}c=a.bq;$p=2;continue _;}b=a.bq;$p=4;continue _;case 1:a:{b:{c:{try{E_(a);if(T()){break _;}}catch($$e){$$je=H($$e);if($$je instanceof By){b=$$je;break c;}else{b=$$je;break b;}}b
=a.bq;$p=3;continue _;}try{C0(Dr(a),a,b);break a;}catch($$e){$$je=H($$e);b=$$je;}}c=a.bq;$p=2;continue _;}b=a.bq;$p=4;continue _;case 2:BV(c);if(T()){break _;}a:{try{Cn(c);Bq(c);break a;}catch($$e){$$je=H($$e);b=$$je;}Bq(c);S(b);}a.bu=0;Bb=Bb-1|0;a.bz=null;c=BQ;if(F!==c)F=c;F.bn=U();S(b);case 3:BV(b);if(T()){break _;}a:{try{Cn(b);Bq(b);break a;}catch($$e){$$je=H($$e);c=$$je;}Bq(b);S(c);}a.bu=0;Bb=Bb-1|0;a.bz=null;b=BQ;if(F!==b)F=b;F.bn=U();return;case 4:BV(b);if(T()){break _;}a:{try{Cn(b);Bq(b);break a;}catch
($$e){$$je=H($$e);c=$$je;}Bq(b);S(c);}a.bu=0;Bb=Bb-1|0;a.bz=null;b=BQ;if(F!==b)F=b;F.bn=U();return;default:Be();}}K().s(a,b,c,$p);},Dj=b=>{if(F!==b)F=b;F.bn=U();},E_=a=>{let b,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=a.bC;if(b===null)return;b=b;$p=1;case 1:Dz(b);if(T()){break _;}return;default:Be();}}K().s(a,b,$p);},Dy=()=>{return F;},DJ=b=>{let $p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:Ej(b);if(T()){break _;}return;default:
Be();}}K().s(b,$p);},DK=(b,c)=>{let d,e;d=F;e=new CT;e.bV=d;e.bU=c;e.b1=B_(e,DH(b,Ba(2147483647))?2147483647:Bj(b));d.bO=e;},Dr=a=>{let b;b=a.b0;if(b!==null)return b;return C9;},Dx=()=>{let b,c,d;b=new Cl;c=null;b.bq=new D;b.bu=1;b.bS=J(10);b.bC=c;d=BC;BC=d+1|0;b.bQ=Ba(d);BQ=b;F=b;BC=1;Bb=1;C9=new CY;},Ej=b=>{let thread=Cx();let javaThread=CO();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback=function(){};callback.e=val=>
{thread.attribute=val;BI(javaThread);thread.resume();};callback.bd=e=>{thread.attribute=Cr(e);BI(javaThread);thread.resume();};callback=Dd(callback);thread.suspend(()=>{try {DK(b,callback);;}catch($e){callback.bd($e);}});return null;};
function Ce(){let a=this;D.call(a);a.bs=0;a.bA=0;a.bw=0;a.bv=0;a.bD=0;}
let Bi=E(Ce),CD=E(0),CY=E(),C0=(a,b,c)=>{c.ba();},D0=E(),BF=b=>{return Math.sin(b);},BO=b=>{return Math.cos(b);},CU=b=>{return Math.sqrt(b);},D_=()=>{return Math.random();},E0=(b,c)=>{return Math.min(b,c);},D7=(b,c)=>{return Math.max(b,c);},Bp=b=>{return Math.sign(b);},Bv=E(0);
function Dq(){D.call(this);this.bJ=null;}
let EH=a=>{let b,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=a.bJ;$p=1;case 1:Ez(b);if(T()){break _;}return;default:Be();}}K().s(a,b,$p);},D5=E(),U=()=>{return Bh((new Date()).getTime());};
function BM(){let a=this;D.call(a);a.bp=null;a.bH=null;a.bg=null;a.bj=0;}
let BP=E(R),Fd=E(),Cj=E(0),E8=E(0),Cz=E(R);
function CB(){D.call(this);this.bI=null;}
let Ey=a=>{D9(a.bI);},E7=E(),Do=E(),Eo=null,CJ=null,BR=null,BH=null,Cv=null,CH=null,CQ=null,BB=()=>{BB=CN(Do);DT();},DT=()=>{let b;Eo=new WeakMap();CJ=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();BR=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();BH=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(BR===null)b=null;else{b=new Ci;b=new FinalizationRegistry(V(!(b instanceof L)?b:b.bi,"accept"));}CH=b;if(BH===null)b=null;else{b=new Ch;b=new FinalizationRegistry(V(!(b instanceof L)?b:b.bi,"accept"));}CQ
=b;},Es=E(),C7=E(0);
function CI(){D.call(this);this.bt=null;}
let Dd=b=>{let c;c=new CI;c.bt=b;return c;},DU=(a,b)=>{a.bt.e(b);},Fc=(a,b)=>{a.bt.bd(b);};
function Db(){let a=this;D.call(a);a.bM=null;a.bN=null;a.bK=0;a.bL=null;}
let DV=E(),Cc=E(0),Ci=E(),EP=(b,c)=>{b;BB();BR.delete(c);},Ch=E(),E2=(b,c)=>{b;BB();BH.delete(c);},Ck=E(BT),Dl=E(0),CG=E(),Ec=a=>{return;},Ds=()=>{let a=new CG();Ec(a);return a;},DZ=(a,b)=>{return;},Bf=(a,b)=>{let c;if(b>0)return D_()*b|0;c=new Cu;X(c);c.bm=1;c.bl=1;S(c);};
function Dm(){let a=this;D.call(a);a.b4=null;a.by=null;a.bT=null;a.bG=null;a.bR=null;a.bP=null;}
let EI=(a,b,c,d)=>{let e,f,g,h,i,j,k;e=Bo(2);f=e.data;a.b4=e;f[0]=b;f[1]=c;g=window.document.createElement("canvas");a.by=g;h=b;g.width=h;i=a.by;g=c;i.height=g;g=a.by.getContext("2d");a.bT=g;j=b;k=c;h=g.createImageData(j,k);a.bG=h;g=new CE;g.bF=Bo(M(b,c));g.bZ=h;a.bR=g;h=new Cw;h.bX=g;a.bP=h;},DA=(a,b,c)=>{let d=new Dm();EI(d,a,b,c);return d;},D3=a=>{return a.bP;},DP=a=>{let b,c,d,e,f,g,h,i,j;b=a.bG.data;c=a.bR.bF;d=0;e=0;while(true){f=c.data;if(d>=f.length)break;g=f[d];h=g>>16&255;b[e]=h;h=e+1|0;i=g>>8&255;b[h]
=i;h=e+2|0;g=g&255;b[h]=g;b[e+3|0]=255;d=d+1|0;e=e+4|0;}j=a.bT;b=a.bG;j.putImageData(b,0.0,0.0);};
function CE(){let a=this;D.call(a);a.bF=null;a.bZ=null;}
let EE=a=>{return a.bF;};
function Cw(){D.call(this);this.bX=null;}
let Eq=a=>{return a.bX;},Fa=E(),CK=E(0);
function CT(){let a=this;D.call(a);a.bV=null;a.bU=null;a.b5=0;a.b1=0;}
let Dv=a=>{let b,c;if(!a.b5){b=a.bV;b.bO=null;if(F!==b)F=b;F.bn=U();c=a.bU;b=null;c.bt.e(b);}},Cu=E(R);
Dw([]);
CV([D,0,0,[],0,3,0,0,0,Cs,0,D,[],3,3,0,0,0,CM,0,D,[],3,3,0,0,0,CL,0,D,[Cs,CM],4,3,0,0,0,Ea,0,D,[],4,3,0,0,0,EL,0,D,[],4,3,0,0,0,By,0,D,[],0,3,0,0,0,I,0,By,[],0,3,0,0,0,R,0,I,[],0,3,0,0,0,E5,0,R,[],0,3,0,0,0,Bz,0,D,[],3,3,0,0,0,BS,0,D,[],3,3,0,0,0,Ca,0,D,[],3,3,0,0,0,O,0,D,[Bz,BS,Ca],0,3,0,0,0,BZ,0,D,[Bz],1,3,0,0,0,Ev,0,BZ,[BS],0,3,0,0,0,Cf,0,D,[Bz,Ca],0,0,0,0,0,Dp,0,D,[],3,3,0,0,0,CZ,0,Cf,[Dp],0,3,0,0,0,D1,0,D,[],0,3,0,0,0,Et,0,D,[],0,3,0,0,0,En,0,D,[],0,3,0,0,0,Dc,0,D,[],0,3,0,P,0,EV,0,D,[],4,3,0,0,0,DS,0,
D,[],0,3,0,0,0,B0,0,D,[],0,3,0,0,0,Cq,0,D,[],3,3,0,0,0,Df,0,B0,[Cq],0,3,0,0,0,Bn,0,D,[],3,3,0,0,0,Z,0,D,[Bn],3,3,0,0,0,B8,0,D,[Z],0,3,0,0,0,L,0,D,[],4,3,0,0,0,B6,0,D,[Z],0,3,0,0,0,B7,0,D,[Z],0,3,0,0,0,B4,0,D,[Z],0,3,0,0,0,B5,0,D,[Z],0,3,0,0,0,B2,0,D,[Z],0,3,0,0,0,B3,0,D,[Z],0,3,0,0,0,B9,0,D,[Z],0,3,0,0,0,B$,0,D,[Z],0,3,0,0,0,EW,0,D,[],0,3,0,0,0,C_,0,D,[],3,3,0,0,0,BU,0,D,[C_],0,3,0,0,0,Cm,0,D,[BS],0,3,0,0,0,DB,0,D,[],4,3,0,0,0,Dn,0,D,[],0,3,0,0,0,BT,0,R,[],0,3,0,0,0,Cl,0,D,[Cq],0,3,0,0,0,Ce,0,D,[],0,3,0,0,0,Bi,
0,Ce,[],0,3,0,0,0]);
CV([CD,0,D,[],3,3,0,0,0,CY,0,D,[CD],0,3,0,0,0,D0,0,D,[],4,3,0,0,0,Bv,0,D,[],3,3,0,0,0,Dq,0,D,[Bv],0,3,0,0,["o",B1(EH)],D5,0,D,[],4,3,0,0,0,BM,0,D,[],0,0,0,0,0,BP,0,R,[],0,3,0,0,0,Fd,0,D,[Bn],1,3,0,0,0,Cj,0,D,[],3,3,0,0,0,E8,0,D,[Bv,Cj],3,0,0,0,0,Cz,0,R,[],0,3,0,0,0,CB,0,D,[Bv],0,3,0,0,["o",B1(Ey)],E7,0,D,[],4,3,0,0,0,Do,0,D,[],0,0,0,BB,0,Es,0,D,[Bn],0,3,0,0,0,C7,0,D,[],3,3,0,0,0,CI,0,D,[C7],0,0,0,0,["e",CS(DU),"bd",CS(Fc)],Db,0,D,[Bv],0,3,0,0,0,DV,0,D,[Bn],1,3,0,0,0,Cc,0,D,[Bn],3,0,0,0,0,Ci,0,D,[Cc],0,3,0,0,
0,Ch,0,D,[Cc],0,3,0,0,0,Ck,0,BT,[],0,3,0,0,0,Dl,0,D,[],3,3,0,0,0,CG,0,D,[Dl,Bz],0,3,0,0,0,Dm,0,D,[],0,3,0,0,0,CE,0,D,[],0,3,0,0,0,Cw,0,D,[],0,3,0,0,0,Fa,0,D,[],0,3,0,0,0,CK,0,D,[],3,3,0,0,0,CT,0,D,[Bv,Cj,CK],0,0,0,0,["o",B1(Dv)],Cu,0,R,[],0,3,0,0,0]);
let D$=Bs(EX),ED=Bs(BW),De=Bs(Cp),Er=Bs(Eb);
Ew(["Can\'t enter monitor from another thread synchronously","<java_object>@","null","game_frame","0","object","function","string","number","undefined","main"]);
O.prototype.toString=function(){return BL(this);};
O.prototype.valueOf=O.prototype.toString;D.prototype.toString=function(){return BL(EN(this));};
D.prototype.__teavm_class__=function(){return EF(this);};
let C=DE(Eh);
C.javaException=DL;
let Fj=Symbol('jsoClass');
(()=>{let c;c=B8.prototype;c.handleEvent=W(ES);c=B6.prototype;c.handleEvent=W(DW);c=B7.prototype;c.handleEvent=W(D4);c=B4.prototype;c.handleEvent=W(Ex);c=B5.prototype;c.handleEvent=W(E6);c=B2.prototype;c.handleEvent=W(EC);c=B3.prototype;c.handleEvent=W(Dt);c=B9.prototype;c.handleEvent=W(Eg);c=B$.prototype;c.handleEvent=W(DI);c=Ci.prototype;c.accept=W(EP);c=Ch.prototype;c.accept=W(E2);})();
B.main=C;}));
