"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let C8=2463534242,D8=()=>{let x=C8;x^=x<<13;x^=x>>>17;x^=x<<5;C8=x;return x;},BX=f=>function(){return f(this);},CL=f=>function(p1){return f(this,p1);},DB=f=>function(){let args=Array.prototype.slice.apply(arguments);C4(function()
{f.apply(this,args);});},Dz=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=BH(W(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Bl(args[i]);}C4(()=>{f.call(null,javaArgs);},callback);},CH=target=>target.$clinit=()=>{},Ev=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName
+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=W();}return function(){superclass.call(this);};},BD=cls=>Eb(cls),W=()=>D,CI=()=>{{return Du();}},BG=t=>{{return De(t);}},X=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},EC=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},CG=(name,binaryName)=>{let cls=EC();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName
=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},BT=CG("char","C"),Ck=CG("int","I"),Z=(a,b)=>a>b?1:a<b? -1:a===b?0:1,M=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Db=BigInt(0),Bb=val=>BigInt.asIntN(64,BigInt(val|0)),Bh=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),Bj=val=>Number(BigInt.asIntN(32,
val))|0,Co=(a,b)=>a>b,DC=(a,b)=>a>=b,CY=(a,b)=>BigInt.asIntN(64,a+b),CP=(a,b)=>BigInt.asIntN(64,a -b),BH=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (BL(cls))(data);},Bw=sz=>new Et(new Uint16Array(sz)),Bv=sz=>new Da(new Int32Array(sz)),CS=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new Da(buffer);},BL=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(W()).call(this);this.data=data;}JavaArray.prototype=Object.create((W()).prototype);JavaArray.prototype.type
=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.b7=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (BL(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta
={item:cls,supertypes:[W()],primitive:false,superclass:W(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},Cc,Em=strings=>{EZ();Cc=new Array(strings.length);for(let i=0;i<strings.length;++i){Cc[i]=CZ(Bl(strings[i]));}},J=index=>Cc[index],B_=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,
i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bl=str=>str===null?null:D0(str),BI=str=>str===null?null:str.bg,EZ=()=>(()=>{})(),CZ;
{CZ=str=>str;}let S=ex=>{throw Cm(ex);},Bs=Symbol("javaException"),Cm=ex=>{if(!ex.$jsException){Y(ex);}return ex.$jsException;},Y=ex=>{let javaCause=ET(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Bd("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bs]=ex;ex.$jsException=err;CQ(err,ex);},CQ=(err,ex)=>{if(typeof DV==="function"&&err.stack){let stack=DV(err.stack);let javaStack
=BH(Eg(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=Er(Bl(element.className),Bl(element.methodName),Bl(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){EK(ex,javaStack);}}},Bd;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Bd=function Bd(message,cause){let self=Reflect.construct(Error,[void 0,cause],Bd);Object.setPrototypeOf(self,Bd.prototype);self[defaultMessage]=message;return self;}
;Bd.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Bd},message:{get(){try {let javaException=this[Bs];if(typeof javaException==='object'){let javaMessage=Dq(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Bd=Error;}let DG=e=>e instanceof Error&&typeof e[Bs]==='object'?e[Bs]:null,G=err=>
{let ex=err[Bs];if(!ex){ex=DP(Bl("(JavaScript) "+err.toString()));err[Bs]=ex;ex.$jsException=err;CQ(err,ex);}return ex;},DP=message=>Ed(message),Dq=t=>EN(t),ET=t=>EY(t),Eg=()=>W(),Er=(className,methodName,fileName,lineNumber)=>{{return null;}},EK=(e,stack)=>{},CJ=null,Ds=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}CJ=packages;},CO=data=>{let packages=CJ;let i=0;while
(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==
0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit
=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}};
function O(runner){this.status=3;this.stack=[];this.suspendCallback=null;this.runner=runner;this.attribute=null;this.completeCallback=null;}
O.prototype.push=function(){for(let i=0;i<arguments.length;++i){this.stack.push(arguments[i]);}return this;};O.prototype.s=O.prototype.push;O.prototype.pop=function(){return this.stack.pop();};O.prototype.l=O.prototype.pop;O.prototype.isResuming=function(){return this.status===2;};O.prototype.isSuspending=function(){return this.status===1;};O.prototype.suspend=function(callback){this.suspendCallback=callback;this.status=1;};O.prototype.start=function(callback){if(this.status!==3){throw new Error("Thread already started");}if
(BA!==null){throw new Error("Another thread is running");}this.status=0;this.completeCallback=callback?callback:result=>{if(result instanceof Error){throw result;}};this.run();};O.prototype.resume=function(){if(BA!==null){throw new Error("Another thread is running");}this.status=2;this.run();};O.prototype.run=function(){BA=this;let result;try {result=this.runner();}catch(e){result=e;}finally {BA=null;}if(this.suspendCallback!==null){let self=this;let callback=this.suspendCallback;this.suspendCallback=null;callback(()=>
self.resume());}else if(this.status===0){this.completeCallback(result);}};let T=()=>{let thread=K();return thread!=null&&thread.isSuspending();},Bg=()=>{let thread=K();return thread!=null&&thread.isResuming();},Cs=()=>{let nativeThread=K();if(nativeThread===null){throw new Error("Suspension point reached from non-threading context "+"(perhaps, from native JS method). See https://teavm.org/docs/runtime/coroutines.html "+"('Interaction with JavaScript' section)");}return nativeThread;},C4=(runner,callback)=>(new O(runner)).start(callback),BA
=null,K=()=>BA,Be=()=>{throw new Error("Invalid recorded state");};
function D(){this.bj=null;this.$id$=0;}
let E_=b=>{let c,d;c=F;if(c===null)return;if(b.bj===null){d=new BJ;d.bh=c;b.bj=d;}b=b.bj;d=b.bh;if(d===null)b.bh=c;else if(d!==c){d=new Cu;Y(d);d.bn=1;d.bm=1;d.bF=J(0);S(d);}b.bk=b.bk+1|0;},E5=b=>{let c,d;if(F===null)return;if(!Bz(b)){c=b.bj;if(c.bh===F){d=c.bk-1|0;c.bk=d;if(!d)c.bh=null;Bz(b);return;}}b=new BM;Y(b);b.bn=1;b.bm=1;S(b);},BS=b=>{let c,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:c=1;$p=1;case 1:Ez(b,c);if(T()){break _;}return;default:Be();}}K().s(b,
c,$p);},Ez=(b,c)=>{let d,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:if(b.bj===null){d=new BJ;d.bh=F;b.bj=d;}d=b.bj;if(d.bh===null)d.bh=F;if(d.bh===F){d.bk=d.bk+c|0;return;}$p=1;case 1:Dx(b,c);if(T()){break _;}return;default:Be();}}K().s(b,c,d,$p);},Ek=(b,c,d)=>{let e,f,g;e=F;f=b.bj;if(f===null){f=new BJ;f.bh=e;b.bj=f;if(e!==e)F=e;F.bo=U();b=b.bj;b.bk=b.bk+c|0;b=null;d.bu.e(b);return;}if(f.bh===null){f.bh=e;if(e!==e)F=e;F.bo=U();b=b.bj;b.bk=b.bk+c|0;b
=null;d.bu.e(b);return;}if(f.bq===null)f.bq=DH();f=f.bq;g=new C9;g.bP=e;g.bQ=b;g.bN=c;g.bO=d;d=g;f.push(d);},Bo=b=>{EA(b,1);},EA=(b,c)=>{let d;if(!Bz(b)){d=b.bj;if(d.bh===F){c=d.bk-c|0;d.bk=c;if(c>0)return;d.bh=null;d=d.bq;if(d!==null&&!(d.length?0:1)){d=new Cv;d.bL=b;B8(d,0);}else Bz(b);return;}}b=new BM;Y(b);b.bn=1;b.bm=1;S(b);},D2=b=>{let c,d,e;if(!Bz(b)){c=b.bj;if(c.bh===null){b=c.bq;if(b!==null&&!(b.length?0:1)){b=c.bq.shift();if(b!==null&&!(b instanceof W()))b=BE(b);d=b;c.bq=null;b=d;c=b.bP;d=b.bQ;e=b.bN;b
=b.bO;if(F!==c)F=c;F.bo=U();d=d.bj;d.bh=c;d.bk=d.bk+e|0;c=null;b.bu.e(c);}return;}}},Bz=a=>{let b,c;b=a.bj;if(b===null)return 1;a:{if(b.bh===null){c=b.bq;if(!(c!==null&&!(c.length?0:1))){b=b.bJ;if(b===null)break a;if(b.length?0:1)break a;}}return 0;}a.bj=null;return 1;},Ec=a=>{return;},ES=()=>{let a=new D();Ec(a);return a;},ED=a=>{let b,c,d,e,f,g,h,i,j;b=a;if(!b.$id$)b.$id$=D8();c=D_(a.$id$,4);b=new CU;b.bs=Bw(16);d=b.bp;e=b;f=J(1);e=e;Ct(e,d,f);Ct(e,b.bp,c===null?J(2):c);f=new N;g=b.bs;h=g.data;i=b.bp;j=h.length;if
(i>=0&&i<=(j-0|0)){f.bg=B_(g.data,0,i);return f;}b=new BQ;D1(b);b.bn=1;b.bm=1;EJ(b);S(b);},Cj=a=>{let b,c;b=a.bj;if(!(b!==null&&b.bh===F?1:0)){b=new BM;Y(b);b.bn=1;b.bm=1;S(b);}b=b.bJ;if(b===null)return;while(!(b.length?0:1)){c=b.shift();if(c!==null&&!(c instanceof W()))c=BE(c);c=c;if(!c.n())B8(c,0);}a.bj.bJ=null;},Dx=(b,c)=>{let thread=Cs();let javaThread=CI();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback=function()
{};callback.e=val=>{thread.attribute=val;BG(javaThread);thread.resume();};callback.bd=e=>{thread.attribute=Cm(e);BG(javaThread);thread.resume();};callback=C_(callback);thread.suspend(()=>{try {Ek(b,c,callback);;}catch($e){callback.bd($e);}});return null;},Cn=E(0),CF=E(0);
function CE(){D.call(this);this.b5=null;}
let Eb=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new CE;c.b5=b;b.classObject=c;}return c;},D4=E(),V=(b,c)=>{let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},EB=E(),E2=b=>{setTimeout(()=>{DB(Dg)(b);},0);},Dg=b=>{let $p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:b.o();if(T()){break _;}return;default:Be();}}K().s(b,
$p);},B8=(b,c)=>{setTimeout(()=>{Dg(b);},c);},DH=()=>{return [];};
function Bt(){let a=this;D.call(a);a.bF=null;a.b2=null;a.bn=0;a.bm=0;}
let EJ=a=>{return a;},D1=a=>{Y(a);},EN=a=>{return a.bF;},EY=a=>{let b;b=a.b2;if(b===a)b=null;return b;},I=E(Bt),R=E(I),DJ=(a,b)=>{Y(a);a.bn=1;a.bm=1;a.bF=b;},Ed=a=>{let b=new R();DJ(b,a);return b;},EU=E(R),Bu=E(0),BP=E(0),B9=E(0),N=E(),Cy=null,C6=null,CW=null,DA=(a,b)=>{a.bg=B_(b.data,0,b.data.length);},E6=a=>{let b=new N();DA(b,a);return b;},D7=(a,b)=>{a.bg=b;},D0=a=>{let b=new N();D7(b,a);return b;},E9=()=>{let b;Cy=Bw(0);b=new N;b.bg="";C6=b;CW=new BR;},BV=E(),El=E(BV),C2=null,EH=b=>{let c,d;if(!b)return 32;c
=0;d=b>>>16|0;if(d)c=16;else d=b;b=d>>>8|0;if(!b)b=d;else c=c|8;d=b>>>4|0;if(!d)d=b;else c=c|4;b=d>>>2|0;if(!b)b=d;else c=c|2;if(b>>>1|0)c=c|1;return (32-c|0)-1|0;},E8=()=>{C2=BD(Ck);};
function Cb(){let a=this;D.call(a);a.bs=null;a.bp=0;}
let Ct=(a,b,c)=>{let d,e,f,g;if(b>=0&&b<=a.bp){if(c===null)c=J(2);else if(c.bg.length?0:1)return a;d=a.bp+c.bg.length|0;DK(a,d);e=a.bp-1|0;while(e>=b){a.bs.data[e+c.bg.length|0]=a.bs.data[e];e=e+(-1)|0;}a.bp=a.bp+c.bg.length|0;e=0;a:{while(e<c.bg.length){f=a.bs;g=b+1|0;if(e<0)break a;if(e>=c.bg.length)break a;f.data[b]=c.bg.charCodeAt(e);e=e+1|0;b=g;}return a;}c=new Cg;Y(c);c.bn=1;c.bm=1;S(c);}c=new Cg;Y(c);c.bn=1;c.bm=1;S(c);},DK=(a,b)=>{let c,d,e,f,g,h;c=a.bs.data;d=c.length;if(d>=b)return;if(d>=1073741823)e
=2147483647;else{f=d*2|0;e=5;if(f>e)e=f;if(b>e)e=b;}g=Bw(e);if(e<d)d=e;h=g.data;b=0;while(b<d){h[b]=c[b];b=b+1|0;}a.bs=g;},Dl=E(0),CU=E(Cb),DU=E(),Ej=E(),Ee=E(),C$=E(),Bk=null,Bq=null,BC=null,H=null,CX=null,Q=null,BU=null,P=()=>{P=CH(C$);EO();},D$=b=>{let c,d,e,f,g,h,i;P();c=window;Bq=c;d=c.document;BC=d;d=d.getElementById(BI(BU));e=Bv(3);b=e.data;Q=e;b[1]=Bq.innerWidth;Q.data[2]=Bq.innerHeight;if(d===null)Dd(BC.body);else if(!(d instanceof HTMLCanvasElement?1:0)){d.removeAttribute("id");Dd(d);}else{H=d;if(d.width)Q.data[1]
=H.width;else H.width=Q.data[1];Q.data[0]=1;if(H.height)Q.data[2]=H.height;else H.height=Q.data[2];Q.data[0]=1;}f=H.getContext("2d");CX=f;c=new CR;c.bU=H;c.bK=f;c.bl=Bv(32767);Bk=c;d=new Ch;f=null;d.br=new D;d.bv=1;d.bT=f;d.bD=c;g=By;By=g+1|0;d.bS=Bb(g);c=new Dm;c.bM=d;E2(c);DY(CX,!!0);H.tabIndex=0;H.focus();c=H;f=new B5;h="addEventListener";d="mousedown";i=!(f instanceof L)?f:f.bi;c[h](d,V(i,"handleEvent"));c=H;f=new B2;h="addEventListener";d="mouseup";i=!(f instanceof L)?f:f.bi;c[h](d,V(i,"handleEvent"));c
=H;f=new B3;h="addEventListener";d="mousemove";i=!(f instanceof L)?f:f.bi;c[h](d,V(i,"handleEvent"));c=H;f=new B0;h="addEventListener";d="mouseleave";i=!(f instanceof L)?f:f.bi;c[h](d,V(i,"handleEvent"));c=H;f=new B1;h="addEventListener";d="contextmenu";i=!(f instanceof L)?f:f.bi;c[h](d,V(i,"handleEvent"));c=H;f=new BY;h="addEventListener";d="keydown";i=!(f instanceof L)?f:f.bi;c[h](d,V(i,"handleEvent"));c=H;f=new BZ;h="addEventListener";d="keyup";i=!(f instanceof L)?f:f.bi;c[h](d,V(i,"handleEvent"));c=Bq;f
=new B6;h="addEventListener";d="resize";i=!(f instanceof L)?f:f.bi;c[h](d,V(i,"handleEvent"));c=BC;f=new B7;c.addEventListener("click",V(!(f instanceof L)?f:f.bi,"handleEvent"));},Dd=b=>{let c,d;P();c=BC.createElement("canvas");H=c;d=BI(BU);c.id=d;d=H;c=Q.data[1];d.width=c;d=H;c=Q.data[2];d.height=c;d=H;b.appendChild(d);},EM=b=>{let c,d,e,f;P();if(Q.data[0]>0)return;c=Bq.innerWidth;d=Bq.innerHeight;b=H;e=c;b.width=e;b=H;e=d;b.height=e;f=Q.data;f[1]=c;f[2]=d;},EG=b=>{let c,d;P();c=new Bi;c.bt=402;d=b.keyCode;if
(d>=65&&d<=90)d=d+32|0;c.bB=d;Bp(Bk,c);b.preventDefault();},D6=b=>{let c,d;P();c=new Bi;c.bt=401;d=b.keyCode;if(d>=65&&d<=90)d=d+32|0;c.bB=d;Bp(Bk,c);b.preventDefault();},Dy=b=>{let c,d;P();c=(B$(H,b.offsetX,b.offsetY)).data;d=new Bi;d.bt=502;d.bx=c[0];d.bw=c[1];d.bE=b.button!=2?0:4;Bp(Bk,d);b.preventDefault();},Ew=b=>{let c,d;P();c=(B$(H,b.offsetX,b.offsetY)).data;d=new Bi;d.bt=501;d.bx=c[0];d.bw=c[1];d.bE=b.button!=2?0:4;Bp(Bk,d);b.preventDefault();},EO=()=>{let b;Cy=Bw(0);b=new N;b.bg="";C6=b;CW=new BR;C2
=BD(Ck);C1=BD(BT);Dc=BH(Ci,128);Dt();BU=J(3);},EL=E(),D_=(b,c)=>{let d,e,f,g,h,i,j,k,l;if(!b)return J(4);d=1<<c;e=d-1|0;f=(((32-EH(b)|0)+c|0)-1|0)/c|0;g=Bw(f);h=g.data;i=M(f-1|0,c);j=0;while(i>=0){k=j+1|0;h[j]=DR((b>>>i|0)&e,d);i=i-c|0;j=k;}l=new N;l.bg=B_(g.data,0,h.length);return l;};
function BW(){let a=this;D.call(a);a.bU=null;a.bK=null;}
let Eq=a=>{return 1;},EE=a=>{let b,c,d;b=new Dj;c=a.bK;d=a.bU;b.bA=c;b.bC=d;return b;},Cl=E(0);
function CR(){BW.call(this);this.bl=null;}
let DQ=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv,bw,bx,by,bz,bA,bB,bC,bD,bE,bF,bG,bH,bI,bJ,bK,bL,bM,bN,bO,bP,bQ,bR,bS,bT,bU,bV,bW,bX,bY,bZ,b0,b1,b2,b3,b4,b5,b6,b7,$$je,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b7=$T.l();b6=$T.l();b5=$T.l();b4=$T.l();b3=$T.l();b2=$T.l();b1=$T.l();b0=$T.l();bZ=$T.l();bY=$T.l();bX=$T.l();bW=$T.l();bV=$T.l();bU=$T.l();bT=$T.l();bS=$T.l();bR=$T.l();bQ=$T.l();bP=$T.l();bO=$T.l();bN=$T.l();bM=$T.l();bL
=$T.l();bK=$T.l();bJ=$T.l();bI=$T.l();bH=$T.l();bG=$T.l();bF=$T.l();bE=$T.l();bD=$T.l();bC=$T.l();bB=$T.l();bA=$T.l();bz=$T.l();by=$T.l();bx=$T.l();bw=$T.l();bv=$T.l();bu=$T.l();bt=$T.l();bs=$T.l();br=$T.l();bq=$T.l();bp=$T.l();bo=$T.l();bn=$T.l();bm=$T.l();bl=$T.l();bk=$T.l();bj=$T.l();bi=$T.l();bh=$T.l();bg=$T.l();bf=$T.l();be=$T.l();bd=$T.l();bc=$T.l();bb=$T.l();ba=$T.l();z=$T.l();y=$T.l();x=$T.l();w=$T.l();v=$T.l();u=$T.l();t=$T.l();s=$T.l();r=$T.l();q=$T.l();p=$T.l();o=$T.l();n=$T.l();m=$T.l();l=$T.l();k
=$T.l();j=$T.l();i=$T.l();h=$T.l();g=$T.l();f=$T.l();e=$T.l();d=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:a:{try{b=Do();c=Dv(214,120,1);d=Eu(Eh(DW(c)));e=Bv(262144);DS(b,Bb(18295169));f=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}g=e.data;while(true){try{if(f>=262144)break;g[f]=((f/64|0)%64|0)<=(32+Bf(b,8)|0)?0:Bf(b,8)+1|0;f=f+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{h=Bv(12288);i=1;}catch($$e){$$je=G($$e);if
($$je instanceof I){break a;}else{throw $$e;}}e=h.data;while(true){try{if(i>=16)break;j=255-Bf(b,96)|0;k=0;while(k<48){l=0;while(l<16){m=9858122;n=Z(i,4);if(!n)m=8355711;if(!(!n&&Bf(b,3)))j=255-Bf(b,96)|0;n=Z(i,1);if(!n&&k<((((M(l,l)*3|0)+(l*81|0)|0)>>2&3)+18|0))m=6990400;else if(!n&&k<((((M(l,l)*3|0)+(l*81|0)|0)>>2&3)+19|0))j=(j*2|0)/3|0;b:{if(i==7){c:{m=6771249;if(l>0&&l<15){if(k>0&&k<15)break c;if(k>32&&k<47)break c;}if(Bf(b,2))break b;j=M(j,150-((l&1)*100|0)|0)/100|0;break b;}m=12359778;o=l-7|0;p=(k&15)
-7|0;if(o<0)o=1-o|0;if(p<0)p=1-p|0;if(p<=o)p=o;j=(196-Bf(b,32)|0)+((p%3|0)*32|0)|0;}}if(i==5){m=11876885;if(!(((l+((k/4|0)*4|0)|0)%8|0)&&(k%4|0)))m=12365733;}q=k<32?j:j/2|0;if(i==8){m=5298487;if(!Bf(b,2)){m=0;q=255;}}n=(M(m>>16&255,q)/255|0)<<16|(M(m>>8&255,q)/255|0)<<8|(M(m&255,q)/255|0);e[(l+(k*16|0)|0)+((i*256|0)*3|0)|0]=n;l=l+1|0;}k=k+1|0;}i=i+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{r=96.5;s=65.0;t=96.5;u=0.0;v=0.0;w=0.0;x=U();y=0;z=0.0;ba=0.0;}catch($$e)
{$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}bb=a;try{bc=z;bd=BB(bc);be=BK(bc);bc=ba;bf=BB(bc);bg=BK(bc);while(Co(CP(U(),x),Bb(10))){h=a.bl.data;if(h[2]>0){bh=(h[2]-428|0)/214.0*2.0;bi=(h[3]-240|0)/120.0*2.0;bj=CN(bh*bh+bi*bi)-1.2000000476837158;if(bj<0.0)bj=0.0;if(bj>0.0){z=z+bh*bj/400.0;ba=ba-bi*bj/400.0;if(ba<(-1.5700000524520874))ba=(-1.5700000524520874);if(ba>1.5700000524520874)ba=1.5700000524520874;}}x=CY(x,Bb(10));h=a.bl.data;bj=0.0+(h[119]-h[115]|0)*0.019999999552965164;bh=0.0+(h[100]
-h[97]|0)*0.019999999552965164;bk=u*0.5;bi=v*0.9900000095367432;bl=w*0.5;u=bk+bd*bj+be*bh;w=bl+be*bj-bd*bh;v=bi+0.003000000026077032;bm=0;while(bm<3){bn=r+u*(((bm+0|0)%3|0)/2|0);bo=bm+1|0;bp=s+v*((bo%3|0)/2|0);bq=t+w*(((bm+2|0)%3|0)/2|0);br=0;d:{e:{while(br<12){bs=(bn+(br>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bt=(bp+((br>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bu=(bq+(br>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bs<0)break e;if(bt<0)break e;if(bu<0)break e;if(bs>=64)break e;if
(bt>=64)break e;if(bu>=64)break e;if(g[(bs+(bt*64|0)|0)+(bu*4096|0)|0]>0)break e;br=br+1|0;}break d;}if(bm!=1){bn=r;bp=s;bq=t;}else if(h[32]>0&&v>0.0){h[32]=0;v=(-0.10000000149011612);bn=r;bp=s;bq=t;}else{v=0.0;bn=r;bp=s;bq=t;}}bm=bo;r=bn;s=bp;t=bq;}}h=a.bl.data;if(h[1]>0&&(-1)>0){g[(-1)]=0;h[1]=0;}if(h[0]>0&&(-1)>0){g[(-1)+y|0]=1;h[0]=0;}bv=0;while(bv<12){q=(r+(bv>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bw=(s+((bv>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bx=(t+(bv>>1&1)*0.6000000238418579
-0.30000001192092896|0)-64|0;if(q>=0&&bw>=0&&bx>=0&&q<64&&bw<64&&bx<64)g[(q+(bw*64|0)|0)+(bx*4096|0)|0]=0;bv=bv+1|0;}by=(-1);bz=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}bj=1.0*bg;bl=1.0*bf;while(true){try{if(bz>=214)break;bk=(bz-107|0)/90.0;bA=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}bB=bk*be;bk=bk*bd;while(true){try{if(bA>=120)break;bC=(bA-60|0)/90.0;bD=bj+bC*bf;bE=bC*bg-bl;bF=bB+bD*bd;bG=bD*be-bk;bH=0;bI=255;bJ=20.0;bK=5.0;bL=0;}catch($$e){$$je
=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}while(true){try{if(bL>=3)break;q=Z(bL,1);bh=q?bF:bE;k=Z(bL,2);if(!k)bh=bG;bw=Z(bh,0.0);if(bw<0)bh= -bh;bM=1.0/bh;bN=bF*bM;bO=bE*bM;bP=bG*bM;bQ=r-(r|0);if(!q)bQ=s-(s|0);if(!k)bQ=t-(t|0);if(bw>0)bQ=1.0-bQ;bR=bM*bQ;bS=r+bN*bQ;bT=s+bO*bQ;bU=t+bP*bQ;if(bw<0){if(!bL)bS=bS-1.0;if(!q)bT=bT-1.0;if(!k)bU=bU-1.0;}}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}o=Z(bO,0.0);f:{try{while(true){bc=bR;if(bc>=bJ)break f;bV=(bS|0)-64|0;bW=(bT|0)-
64|0;bX=(bU|0)-64|0;if(bV<0)break f;if(bW<0)break f;if(bX<0)break f;if(bV>=64)break f;if(bW>=64)break f;if(bX>=64)break;bY=(bV+(bW*64|0)|0)+(bX*4096|0)|0;bZ=g[bY];if(bZ>0){j=((bS+bU)*16.0|0)&15;k=((bT*16.0|0)&15)+16|0;if(!q){j=(bS*16.0|0)&15;k=(bU*16.0|0)&15;if(o<0)k=k+32|0;}g:{b0=16777215;if(bY==(-1)){if(j<=0)break g;n=k%16|0;if(n<=0)break g;if(j>=15)break g;if(n>=15)break g;}b0=e[(j+(k*16|0)|0)+((bZ*256|0)*3|0)|0];}if(bR>=bK)bY=by;else if(bz!=(h[2]/4|0))bY=by;else if(bA!=(h[3]/4|0))bY=by;else{b1=1;if(bw>0)b1
=(-1);y=b1<<(6*bL|0);bK=bR;}if(b0<=0)by=bY;else{bI=M(255-(bR/20.0*255.0|0)|0,255-(((bL+2|0)%3|0)*50|0)|0)/255|0;by=bY;bH=b0;bJ=bc;}}bS=bS+bN;bT=bT+bO;bU=bU+bP;bR=bR+bM;}break f;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bL=bL+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b2=d.data;b3=M(bH>>16&255,bI)/255|0;b4=M(bH>>8&255,bI)/255|0;b5=M(bH&255,bI)/255|0;b2[bz+(bA*214|0)|0]=b3<<16|b4<<8|b5;bA=bA+1|0;continue;}catch($$e){$$je=G($$e);if
($$je instanceof I){break a;}else{throw $$e;}}}try{bz=bz+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b6=Bb(2);$p=1;continue _;}catch($$e){$$je=G($$e);if($$je instanceof I){}else{throw $$e;}}}return;case 1:a:{h:{try{DE(b6);if(T()){break _;}if(Eq(bb))break h;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}return;}try{EQ(EE(bb),c,0,0,856,480,null);b7=by;bc=z;bd=BB(bc);be=BK(bc);bc=ba;bf=BB(bc);bg=BK(bc);while(Co(CP(U(),x),Bb(10))){h=a.bl.data;if
(h[2]>0){bh=(h[2]-428|0)/214.0*2.0;bi=(h[3]-240|0)/120.0*2.0;bj=CN(bh*bh+bi*bi)-1.2000000476837158;if(bj<0.0)bj=0.0;if(bj>0.0){z=z+bh*bj/400.0;ba=ba-bi*bj/400.0;if(ba<(-1.5700000524520874))ba=(-1.5700000524520874);if(ba>1.5700000524520874)ba=1.5700000524520874;}}x=CY(x,Bb(10));h=a.bl.data;bj=0.0+(h[119]-h[115]|0)*0.019999999552965164;bh=0.0+(h[100]-h[97]|0)*0.019999999552965164;bk=u*0.5;bi=v*0.9900000095367432;bl=w*0.5;u=bk+bd*bj+be*bh;w=bl+be*bj-bd*bh;v=bi+0.003000000026077032;bm=0;while(bm<3){bn=r+u*(((bm
+0|0)%3|0)/2|0);bo=bm+1|0;bp=s+v*((bo%3|0)/2|0);bq=t+w*(((bm+2|0)%3|0)/2|0);br=0;i:{j:{while(br<12){bs=(bn+(br>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bt=(bp+((br>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bu=(bq+(br>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(bs<0)break j;if(bt<0)break j;if(bu<0)break j;if(bs>=64)break j;if(bt>=64)break j;if(bu>=64)break j;if(g[(bs+(bt*64|0)|0)+(bu*4096|0)|0]>0)break j;br=br+1|0;}break i;}if(bm!=1){bn=r;bp=s;bq=t;}else if(h[32]>0&&v>0.0)
{h[32]=0;v=(-0.10000000149011612);bn=r;bp=s;bq=t;}else{v=0.0;bn=r;bp=s;bq=t;}}bm=bo;r=bn;s=bp;t=bq;}}h=a.bl.data;if(h[1]>0&&b7>0){g[b7]=0;h[1]=0;}if(h[0]>0&&b7>0){g[b7+y|0]=1;h[0]=0;}bv=0;while(bv<12){q=(r+(bv>>0&1)*0.6000000238418579-0.30000001192092896|0)-64|0;bw=(s+((bv>>2)-1|0)*0.800000011920929+0.6499999761581421|0)-64|0;bx=(t+(bv>>1&1)*0.6000000238418579-0.30000001192092896|0)-64|0;if(q>=0&&bw>=0&&bx>=0&&q<64&&bw<64&&bx<64)g[(q+(bw*64|0)|0)+(bx*4096|0)|0]=0;bv=bv+1|0;}by=(-1);bz=0;}catch($$e){$$je=G($$e);if
($$je instanceof I){break a;}else{throw $$e;}}bj=1.0*bg;bl=1.0*bf;while(true){try{if(bz>=214)break;bk=(bz-107|0)/90.0;bA=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}bB=bk*be;bk=bk*bd;while(true){try{if(bA>=120)break;bC=(bA-60|0)/90.0;bD=bj+bC*bf;bE=bC*bg-bl;bF=bB+bD*bd;bG=bD*be-bk;bH=0;bI=255;bJ=20.0;bK=5.0;bL=0;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}while(true){try{if(bL>=3)break;q=Z(bL,1);bh=q?bF:bE;k=Z(bL,2);if(!k)bh=bG;bw=Z(bh,0.0);if(bw<0)bh
= -bh;bM=1.0/bh;bN=bF*bM;bO=bE*bM;bP=bG*bM;bQ=r-(r|0);if(!q)bQ=s-(s|0);if(!k)bQ=t-(t|0);if(bw>0)bQ=1.0-bQ;bR=bM*bQ;bS=r+bN*bQ;bT=s+bO*bQ;bU=t+bP*bQ;if(bw<0){if(!bL)bS=bS-1.0;if(!q)bT=bT-1.0;if(!k)bU=bU-1.0;}}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}o=Z(bO,0.0);k:{try{while(true){bc=bR;if(bc>=bJ)break k;bV=(bS|0)-64|0;bW=(bT|0)-64|0;bX=(bU|0)-64|0;if(bV<0)break k;if(bW<0)break k;if(bX<0)break k;if(bV>=64)break k;if(bW>=64)break k;if(bX>=64)break;bY=(bV+(bW*64|0)|0)+(bX*4096|0)|0;bZ
=g[bY];if(bZ>0){j=((bS+bU)*16.0|0)&15;k=((bT*16.0|0)&15)+16|0;if(!q){j=(bS*16.0|0)&15;k=(bU*16.0|0)&15;if(o<0)k=k+32|0;}l:{b0=16777215;if(bY==b7){if(j<=0)break l;n=k%16|0;if(n<=0)break l;if(j>=15)break l;if(n>=15)break l;}b0=e[(j+(k*16|0)|0)+((bZ*256|0)*3|0)|0];}if(bR>=bK)bY=by;else if(bz!=(h[2]/4|0))bY=by;else if(bA!=(h[3]/4|0))bY=by;else{b1=1;if(bw>0)b1=(-1);y=b1<<(6*bL|0);bK=bR;}if(b0<=0)by=bY;else{bI=M(255-(bR/20.0*255.0|0)|0,255-(((bL+2|0)%3|0)*50|0)|0)/255|0;by=bY;bH=b0;bJ=bc;}}bS=bS+bN;bT=bT+bO;bU=bU
+bP;bR=bR+bM;}break k;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bL=bL+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b2=d.data;b3=M(bH>>16&255,bI)/255|0;b4=M(bH>>8&255,bI)/255|0;b5=M(bH&255,bI)/255|0;b2[bz+(bA*214|0)|0]=b3<<16|b4<<8|b5;bA=bA+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{bz=bz+1|0;continue;}catch($$e){$$je=G($$e);if($$je instanceof I){break a;}else{throw $$e;}}}try{b6=Bb(2);continue _;}
catch($$e){$$je=G($$e);if($$je instanceof I){}else{throw $$e;}}}return;default:Be();}}K().s(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv,bw,bx,by,bz,bA,bB,bC,bD,bE,bF,bG,bH,bI,bJ,bK,bL,bM,bN,bO,bP,bQ,bR,bS,bT,bU,bV,bW,bX,bY,bZ,b0,b1,b2,b3,b4,b5,b6,b7,$p);},Bp=(a,b)=>{let c,d;a:{b:{c:{c=0;switch(b.bt){case 401:c=1;break c;case 501:c=1;d=a.bl.data;d[2]=b.bx;d[3]=b.bw;break b;case 503:case 506:d=a.bl.data;d[2]=b.bx;d[3]=b.bw;break a;case 505:break;case 402:break c;case 502:break b;default:break a;}a.bl.data[2]
=0;break a;}a.bl.data[b.bB]=c;break a;}if((b.bE&4)<=0)a.bl.data[0]=c;else a.bl.data[1]=c;}return 1;},EP=E(),B$=(b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o;e=b.width;f=b.height;g=Df(e/214.0,f/120.0);h=214.0*g;i=Bj(Bh(h+Bn(h)*0.5));h=120.0*g;j=Bj(Bh(h+Bn(h)*0.5));k=(e-i|0)/2|0;l=(f-j|0)/2|0;if(c>=k&&c<(k+i|0)&&d>=l&&d<(l+j|0)){h=(c-k|0)/i;m=(d-l|0)/j;h=h*856.0;n=Bj(Bh(h+Bn(h)*0.5));h=m*480.0;o=Bj(Bh(h+Bn(h)*0.5));if(n<0)n=0;else if(n>855)n=855;if(o<0)o=0;else if(o>479)o=479;return CS([n,o]);}return CS([(-1),(-1)]);},DY
=(b,c)=>{b.imageSmoothingEnabled=c;if(b.mozImageSmoothingEnabled!==undefined)b.mozImageSmoothingEnabled=c;if(b.webkitImageSmoothingEnabled!==undefined)b.webkitImageSmoothingEnabled=c;if(b.msImageSmoothingEnabled!==undefined)b.msImageSmoothingEnabled=c;},Bm=E(0),Ba=E(0),B5=E(),EI=(b,c)=>{b;Ew(c);};
function L(){D.call(this);this.bi=null;}
let BE=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=Bl(typeof b);if(c===J(5))d=1;else if(!(J(5) instanceof N))d=0;else{e=J(5);d=c.bg!==e.bg?0:1;}a:{if(!d){if(c===J(6))d=1;else if(!(J(6) instanceof N))d=0;else{e=J(6);d=c.bg!==e.bg?0:1;}if(!d){d=0;break a;}}d=1;}Bx();e=CC;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bi=b;e.set(b,new WeakRef(h));return h;}if(c===J(7))d=1;else if(!(J(7) instanceof N))d=0;else{e=J(7);d=
c.bg!==e.bg?0:1;}if(d){i=BO;j=CA;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bi=b;k=h;i.set(b,new WeakRef(k));C0(j,k,b);return h;}if(c===J(8))d=1;else if(!(J(8) instanceof N))d=0;else{e=J(8);d=c.bg!==e.bg?0:1;}if(d){l=BF;m=CK;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bi=b;k=h;l.set(b,new WeakRef(k));C0(m,k,b);return h;}if(c===J(9))d=1;else if(!(J(9) instanceof N))d=0;else{e=J(9);d
=c.bg!==e.bg?0:1;}if(d){f=Cq;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=new L;h.bi=b;Cq=new WeakRef(h);return h;}}e=new L;e.bi=b;return e;},C0=(b,c,d)=>{return b.register(c,d);},B2=E(),DO=(b,c)=>{b;Dy(c);},B3=E(),DX=(b,c)=>{let d;b;P();d=(B$(H,c.offsetX,c.offsetY)).data;b=new Bi;b.bt=503;b.bx=d[0];b.bw=d[1];Bp(Bk,b);},B0=E(),En=(b,c)=>{b;P();b=new Bi;b.bt=505;Bp(Bk,b);},B1=E(),EV=(b,c)=>{b;P();c.preventDefault();},BY=E(),Es=(b,c)=>{b;D6(c);},BZ=E(),Dp=(b,c)=>{b;EG(c);},B6=E(),D9=
(b,c)=>{b;EM(c);},B7=E(),DD=(b,c)=>{b;P();H.focus();},C7=E(0),BR=E(),Ci=E(),C1=null,Dc=null,DR=(b,c)=>{if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},E7=()=>{C1=BD(BT);Dc=BH(Ci,128);},Dw=E(),BQ=E(R);
function Ch(){let a=this;D.call(a);a.b0=null;a.bS=Db;a.bo=Db;a.br=null;a.bR=null;a.bz=null;a.bT=null;a.bv=0;a.bD=null;}
let BN=null,F=null,By=0,Bc=0,C5=null,Ep=a=>{let b,c,$$je,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();c=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:a:{try{try{Bc=Bc+1|0;De(a);a.bz=ES();$p=1;continue _;}catch($$e){$$je=G($$e);if($$je instanceof Bt){b=$$je;}else{throw $$e;}}CV(Dn(a),a,b);break a;}catch($$e){$$je=G($$e);b=$$je;}c=a.br;$p=2;continue _;}b=a.br;$p=4;continue _;case 1:a:{b:{c:{try{E0(a);if(T()){break _;}}catch($$e){$$je=G($$e);if($$je instanceof Bt){b=$$je;break c;}else{b=$$je;break b;}}b
=a.br;$p=3;continue _;}try{CV(Dn(a),a,b);break a;}catch($$e){$$je=G($$e);b=$$je;}}c=a.br;$p=2;continue _;}b=a.br;$p=4;continue _;case 2:BS(c);if(T()){break _;}a:{try{Cj(c);Bo(c);break a;}catch($$e){$$je=G($$e);b=$$je;}Bo(c);S(b);}a.bv=0;Bc=Bc-1|0;a.bz=null;c=BN;if(F!==c)F=c;F.bo=U();S(b);case 3:BS(b);if(T()){break _;}a:{try{Cj(b);Bo(b);break a;}catch($$e){$$je=G($$e);c=$$je;}Bo(b);S(c);}a.bv=0;Bc=Bc-1|0;a.bz=null;b=BN;if(F!==b)F=b;F.bo=U();return;case 4:BS(b);if(T()){break _;}a:{try{Cj(b);Bo(b);break a;}catch
($$e){$$je=G($$e);c=$$je;}Bo(b);S(c);}a.bv=0;Bc=Bc-1|0;a.bz=null;b=BN;if(F!==b)F=b;F.bo=U();return;default:Be();}}K().s(a,b,c,$p);},De=b=>{if(F!==b)F=b;F.bo=U();},E0=a=>{let b,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=a.bD;if(b===null)return;b=b;$p=1;case 1:DQ(b);if(T()){break _;}return;default:Be();}}K().s(a,b,$p);},Du=()=>{return F;},DE=b=>{let $p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:Ea(b);if(T()){break _;}return;default:
Be();}}K().s(b,$p);},DF=(b,c)=>{let d,e;d=F;e=new CM;e.bX=d;e.bW=c;e.b1=B8(e,DC(b,Bb(2147483647))?2147483647:Bj(b));d.bR=e;},Dn=a=>{let b;b=a.b0;if(b!==null)return b;return C5;},Dt=()=>{let b,c,d;b=new Ch;c=null;b.br=new D;b.bv=1;b.bT=J(10);b.bD=c;d=By;By=d+1|0;b.bS=Bb(d);BN=b;F=b;By=1;Bc=1;C5=new CT;},Ea=b=>{let thread=Cs();let javaThread=CI();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback=function(){};callback.e=val=>
{thread.attribute=val;BG(javaThread);thread.resume();};callback.bd=e=>{thread.attribute=Cm(e);BG(javaThread);thread.resume();};callback=C_(callback);thread.suspend(()=>{try {DF(b,callback);;}catch($e){callback.bd($e);}});return null;};
function Ca(){let a=this;D.call(a);a.bt=0;a.bB=0;a.bx=0;a.bw=0;a.bE=0;}
let Bi=E(Ca),Cw=E(0),CT=E(),CV=(a,b,c)=>{c.ba();},DT=E(),BB=b=>{return Math.sin(b);},BK=b=>{return Math.cos(b);},CN=b=>{return Math.sqrt(b);},D3=()=>{return Math.random();},Df=(b,c)=>{return Math.min(b,c);},Bn=b=>{return Math.sign(b);},Br=E(0);
function Dm(){D.call(this);this.bM=null;}
let Ex=a=>{let b,$p,$z;$p=0;if(Bg()){let $T=K();$p=$T.l();b=$T.l();a=$T.l();}_:while(true){switch($p){case 0:b=a.bM;$p=1;case 1:Ep(b);if(T()){break _;}return;default:Be();}}K().s(a,b,$p);},DZ=E(),U=()=>{return Bh((new Date()).getTime());};
function BJ(){let a=this;D.call(a);a.bq=null;a.bJ=null;a.bh=null;a.bk=0;}
let BM=E(R),E4=E(),Cf=E(0),EX=E(0),Cu=E(R);
function Cv(){D.call(this);this.bL=null;}
let Eo=a=>{D2(a.bL);},EW=E(),Dk=E(),Ef=null,CC=null,BO=null,BF=null,Cq=null,CA=null,CK=null,Bx=()=>{Bx=CH(Dk);DL();},DL=()=>{let b;Ef=new WeakMap();CC=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();BO=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();BF=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(BO===null)b=null;else{b=new Ce;b=new FinalizationRegistry(V(!(b instanceof L)?b:b.bi,"accept"));}CA=b;if(BF===null)b=null;else{b=new Cd;b=new FinalizationRegistry(V(!(b instanceof L)?b:b.bi,"accept"));}CK
=b;},Ei=E(),C3=E(0);
function CB(){D.call(this);this.bu=null;}
let C_=b=>{let c;c=new CB;c.bu=b;return c;},DM=(a,b)=>{a.bu.e(b);},E3=(a,b)=>{a.bu.bd(b);};
function C9(){let a=this;D.call(a);a.bP=null;a.bQ=null;a.bN=0;a.bO=null;}
let DN=E(),B4=E(0),Ce=E(),EF=(b,c)=>{c=c===null?null:c instanceof W()?c:BE(c);b;Bx();b=BO;c=c===null?null:!(c instanceof L)?c:c.bi;b.delete(c);},Cd=E(),ER=(b,c)=>{c=c===null?null:c instanceof W()?c:BE(c);b;Bx();b=BF;c=c===null?null:!(c instanceof L)?c:c.bi;b.delete(c);},Cg=E(BQ),Dh=E(0),Cz=E(),D5=a=>{return;},Do=()=>{let a=new Cz();D5(a);return a;},DS=(a,b)=>{return;},Bf=(a,b)=>{let c;if(b>0)return D3()*b|0;c=new Cp;Y(c);c.bn=1;c.bm=1;S(c);};
function Di(){let a=this;D.call(a);a.b6=0;a.b3=0;a.by=null;a.bV=null;a.bI=null;a.bG=null;}
let Ey=(a,b,c,d)=>{let e,f,g,h,i;a.b6=b;a.b3=c;e=window.document.createElement("canvas");a.by=e;f=b;e.width=f;g=a.by;e=c;g.height=e;e=a.by.getContext("2d");a.bV=e;h=b;i=c;f=e.createImageData(h,i);a.bI=f;e=new Cx;e.bH=Bv(M(b,c));e.bZ=f;a.bG=e;},Dv=(a,b,c)=>{let d=new Di();Ey(d,a,b,c);return d;},DW=a=>{let b;b=new Cr;b.bY=a.bG;return b;},DI=a=>{let b,c,d,e,f,g,h,i,j;b=a.bI.data;c=a.bG.bH;d=0;e=0;while(true){f=c.data;if(d>=f.length)break;g=f[d];h=g>>16&255;b[e]=h;h=e+1|0;i=g>>8&255;b[h]=i;h=e+2|0;g=g&255;b[h]=
g;b[e+3|0]=255;d=d+1|0;e=e+4|0;}j=a.bV;b=a.bI;j.putImageData(b,0.0,0.0);};
function Cx(){let a=this;D.call(a);a.bH=null;a.bZ=null;}
let Eu=a=>{return a.bH;};
function Cr(){D.call(this);this.bY=null;}
let Eh=a=>{return a.bY;};
function Dj(){let a=this;D.call(a);a.bA=null;a.bC=null;}
let EQ=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m;if(e==856&&f==480){h=a.bC.width;i=a.bC.height;j=h;k=j/214.0;l=i;m=Df(k,l/120.0);k=214.0*m;e=Bj(Bh(k+Bn(k)*0.5));k=120.0*m;f=Bj(Bh(k+Bn(k)*0.5));c=(h-e|0)/2|0;d=(i-f|0)/2|0;a.bA.clearRect(0.0,0.0,j,l);}DI(b);g=a.bA;b=b.by;j=c;l=d;k=e;m=f;g.drawImage(b,j,l,k,m);},E1=E(),CD=E(0);
function CM(){let a=this;D.call(a);a.bX=null;a.bW=null;a.b4=0;a.b1=0;}
let Dr=a=>{let b,c;if(!a.b4){b=a.bX;b.bR=null;if(F!==b)F=b;F.bo=U();c=a.bW;b=null;c.bu.e(b);}},Cp=E(R);
Ds([]);
CO([D,0,0,[],0,3,0,0,0,Cn,0,D,[],3,3,0,0,0,CF,0,D,[],3,3,0,0,0,CE,0,D,[Cn,CF],4,3,0,0,0,D4,0,D,[],4,3,0,0,0,EB,0,D,[],4,3,0,0,0,Bt,0,D,[],0,3,0,0,0,I,0,Bt,[],0,3,0,0,0,R,0,I,[],0,3,0,0,0,EU,0,R,[],0,3,0,0,0,Bu,0,D,[],3,3,0,0,0,BP,0,D,[],3,3,0,0,0,B9,0,D,[],3,3,0,0,0,N,0,D,[Bu,BP,B9],0,3,0,0,0,BV,0,D,[Bu],1,3,0,0,0,El,0,BV,[BP],0,3,0,0,0,Cb,0,D,[Bu,B9],0,0,0,0,0,Dl,0,D,[],3,3,0,0,0,CU,0,Cb,[Dl],0,3,0,0,0,DU,0,D,[],0,3,0,0,0,Ej,0,D,[],0,3,0,0,0,Ee,0,D,[],0,3,0,0,0,C$,0,D,[],0,3,0,P,0,EL,0,D,[],4,3,0,0,0,BW,0,
D,[],0,3,0,0,0,Cl,0,D,[],3,3,0,0,0,CR,0,BW,[Cl],0,3,0,0,0,EP,0,D,[],0,3,0,0,0,Bm,0,D,[],3,3,0,0,0,Ba,0,D,[Bm],3,3,0,0,0,B5,0,D,[Ba],0,3,0,0,0,L,0,D,[],4,3,0,0,0,B2,0,D,[Ba],0,3,0,0,0,B3,0,D,[Ba],0,3,0,0,0,B0,0,D,[Ba],0,3,0,0,0,B1,0,D,[Ba],0,3,0,0,0,BY,0,D,[Ba],0,3,0,0,0,BZ,0,D,[Ba],0,3,0,0,0,B6,0,D,[Ba],0,3,0,0,0,B7,0,D,[Ba],0,3,0,0,0,C7,0,D,[],3,3,0,0,0,BR,0,D,[C7],0,3,0,0,0,Ci,0,D,[BP],0,3,0,0,0,Dw,0,D,[],4,3,0,0,0,BQ,0,R,[],0,3,0,0,0,Ch,0,D,[Cl],0,3,0,0,0,Ca,0,D,[],0,3,0,0,0,Bi,0,Ca,[],0,3,0,0,0,Cw,0,D,[],
3,3,0,0,0,CT,0,D,[Cw],0,3,0,0,0]);
CO([DT,0,D,[],4,3,0,0,0,Br,0,D,[],3,3,0,0,0,Dm,0,D,[Br],0,3,0,0,["o",BX(Ex)],DZ,0,D,[],4,3,0,0,0,BJ,0,D,[],0,0,0,0,0,BM,0,R,[],0,3,0,0,0,E4,0,D,[Bm],1,3,0,0,0,Cf,0,D,[],3,3,0,0,0,EX,0,D,[Br,Cf],3,0,0,0,0,Cu,0,R,[],0,3,0,0,0,Cv,0,D,[Br],0,3,0,0,["o",BX(Eo)],EW,0,D,[],4,3,0,0,0,Dk,0,D,[],0,0,0,Bx,0,Ei,0,D,[Bm],0,3,0,0,0,C3,0,D,[],3,3,0,0,0,CB,0,D,[C3],0,0,0,0,["e",CL(DM),"bd",CL(E3)],C9,0,D,[Br],0,3,0,0,0,DN,0,D,[Bm],1,3,0,0,0,B4,0,D,[Bm],3,3,0,0,0,Ce,0,D,[B4],0,3,0,0,0,Cd,0,D,[B4],0,3,0,0,0,Cg,0,BQ,[],0,3,0,
0,0,Dh,0,D,[],3,3,0,0,0,Cz,0,D,[Dh,Bu],0,3,0,0,0,Di,0,D,[],0,3,0,0,0,Cx,0,D,[],0,3,0,0,0,Cr,0,D,[],0,3,0,0,0,Dj,0,D,[],0,3,0,0,0,E1,0,D,[],0,3,0,0,0,CD,0,D,[],3,3,0,0,0,CM,0,D,[Br,Cf,CD],0,0,0,0,["o",BX(Dr)],Cp,0,R,[],0,3,0,0,0]);
let Et=BL(BT),Da=BL(Ck);
Em(["Can\'t enter monitor from another thread synchronously","<java_object>@","null","game_frame","0","object","function","string","number","undefined","main"]);
N.prototype.toString=function(){return BI(this);};
N.prototype.valueOf=N.prototype.toString;D.prototype.toString=function(){return BI(ED(this));};
D.prototype.__teavm_class__=function(){return Ev(this);};
let C=Dz(D$);
C.javaException=DG;
let E$=Symbol('jsoClass');
(()=>{let c;c=B5.prototype;c.handleEvent=X(EI);c=B2.prototype;c.handleEvent=X(DO);c=B3.prototype;c.handleEvent=X(DX);c=B0.prototype;c.handleEvent=X(En);c=B1.prototype;c.handleEvent=X(EV);c=BY.prototype;c.handleEvent=X(Es);c=BZ.prototype;c.handleEvent=X(Dp);c=B6.prototype;c.handleEvent=X(D9);c=B7.prototype;c.handleEvent=X(DD);c=Ce.prototype;c.accept=X(EF);c=Cd.prototype;c.accept=X(ER);})();
B.main=C;}));
